=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for F::Api::ApprovalsMaterializedApprovalsFlowsRejectResourcePostRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe F::Api::ApprovalsMaterializedApprovalsFlowsRejectResourcePostRequest do
  #let(:instance) { F::Api::ApprovalsMaterializedApprovalsFlowsRejectResourcePostRequest.new }

  describe 'test an instance of ApprovalsMaterializedApprovalsFlowsRejectResourcePostRequest' do
    it 'should create an instance of ApprovalsMaterializedApprovalsFlowsRejectResourcePostRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(F::Api::ApprovalsMaterializedApprovalsFlowsRejectResourcePostRequest)
    end
  end

  describe 'test attribute "resource_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "resource_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
