=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-10-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for F::Api::PerformanceAgreementSelfCommentsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe F::Api::PerformanceAgreementSelfCommentsInner do
  #let(:instance) { F::Api::PerformanceAgreementSelfCommentsInner.new }

  describe 'test an instance of PerformanceAgreementSelfCommentsInner' do
    it 'should create an instance of PerformanceAgreementSelfCommentsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(F::Api::PerformanceAgreementSelfCommentsInner)
    end
  end

  describe 'test attribute "question_uuid"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "author_access_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "text"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "updated_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
