=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for F::PerformanceReviewEvaluationsGetWithTargetsManagedByFilterParameter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe F::PerformanceReviewEvaluationsGetWithTargetsManagedByFilterParameter do
  #let(:instance) { F::PerformanceReviewEvaluationsGetWithTargetsManagedByFilterParameter.new }

  describe 'test an instance of PerformanceReviewEvaluationsGetWithTargetsManagedByFilterParameter' do
    it 'should create an instance of PerformanceReviewEvaluationsGetWithTargetsManagedByFilterParameter' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(F::PerformanceReviewEvaluationsGetWithTargetsManagedByFilterParameter)
    end
  end

  describe 'test attribute "manager_employee_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "only_direct_reports"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
