# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'pry-byebug'
  gem 'rake', '~> 13.0.1'
  gem 'rspec', '~> 3.6'
  gem 'rubocop', '~> 1.60'
end
