---
generatorName: ruby
inputSpec: oas-2026-07-01.normalized.yaml
outputDir: "."
additionalProperties:
  gemName: factorial_api
  moduleName: F
  sdkMajorMinor: '1.0'
  gemVersion: 1.0.2026.7.1.0
  library: faraday
  gemLicense: MIT
  gemHomepage: https://github.com/factorialco/factorial-api-sdks
  gemSummary: Ruby SDK for the Factorial public API
