# frozen_string_literal: true

require 'bundler/gem_tasks'

begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)
  task default: :spec
rescue LoadError
  # no rspec available
end

desc 'Regenerate the SDK (VERSION=yyyy-mm-dd, SPEC=local-file, SET_VERSION=X.Y.Z)'
task :generate do
  args = []
  args << ENV['SPEC'] if ENV['SPEC']
  args << "--version=#{ENV['VERSION']}" if ENV['VERSION']
  args << "--set-version=#{ENV['SET_VERSION']}" if ENV['SET_VERSION']
  sh 'ruby', 'scripts/generate_sdk.rb', *args
end
