=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-10-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'cgi'

module F::Api
  class ProcessesMaterializedProcessApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Creates a Materialized process
    # Creates a Materialized process
    # @param [Hash] opts the optional parameters
    # @option opts [ProcessesMaterializedProcessesPostRequest] :processes_materialized_processes_post_request 
    # @return [ProcessesMaterializedProcess]
    def processes_materialized_processes_post(opts = {})
      data, _status_code, _headers = processes_materialized_processes_post_with_http_info(opts)
      data
    end

    # Creates a Materialized process
    # Creates a Materialized process
    # @param [Hash] opts the optional parameters
    # @option opts [ProcessesMaterializedProcessesPostRequest] :processes_materialized_processes_post_request 
    # @return [Array<(ProcessesMaterializedProcess, Integer, Hash)>] ProcessesMaterializedProcess data, response status code and response headers
    def processes_materialized_processes_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ProcessesMaterializedProcessApi.processes_materialized_processes_post ...'
      end
      # resource path
      local_var_path = '/api/2026-10-01/resources/processes/materialized_processes'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'processes_materialized_processes_post_request'])

      # return_type
      return_type = opts[:debug_return_type] || 'ProcessesMaterializedProcess'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apikey', 'oauth2']

      new_options = opts.merge(
        :operation => :"ProcessesMaterializedProcessApi.processes_materialized_processes_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ProcessesMaterializedProcessApi#processes_materialized_processes_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
