=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-10-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for F::Api::CompensationsPayrollRunEmployeesCompensationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CompensationsPayrollRunEmployeesCompensationApi' do
  before do
    # run before each test
    @api_instance = F::Api::CompensationsPayrollRunEmployeesCompensationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CompensationsPayrollRunEmployeesCompensationApi' do
    it 'should create an instance of CompensationsPayrollRunEmployeesCompensationApi' do
      expect(@api_instance).to be_instance_of(F::Api::CompensationsPayrollRunEmployeesCompensationApi)
    end
  end

  # unit tests for compensations_payroll_run_employees_compensations_get
  # Reads all Payroll run employees compensations
  # Retrieves payroll-run employee compensation records.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :ids Payroll run employee compensation ids
  # @option opts [Array<String>] :payroll_run_ids Filter by payroll run ids, refers to compensations/payroll_runs endpoint.
  # @option opts [Array<String>] :payroll_run_employee_ids Filter by employee ids (participants of the payroll run)
  # @option opts [Array<String>] :payroll_concept_ids Filter by payroll concept ids, refers to compensations/concepts endpoint.
  # @option opts [String] :result_type Filter by record projection type — &#x60;compensation&#x60; (input) or &#x60;payroll_result&#x60; (computed)
  # @option opts [Array<String>] :legal_entity_ids Filter by legal entity ids, refers to companies/legal_entities endpoint.
  # @return [CompensationsPayrollRunEmployeesCompensationsGet200Response]
  describe 'compensations_payroll_run_employees_compensations_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for compensations_payroll_run_employees_compensations_id_get
  # Reads a single Payroll run employees compensation
  # Retrieves payroll-run employee compensation records.
  # @param id Payroll run employee compensation ids
  # @param [Hash] opts the optional parameters
  # @return [CompensationsPayrollRunEmployeesCompensation]
  describe 'compensations_payroll_run_employees_compensations_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
