=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for F::CustomResourcesValueApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomResourcesValueApi' do
  before do
    # run before each test
    @api_instance = F::CustomResourcesValueApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomResourcesValueApi' do
    it 'should create an instance of CustomResourcesValueApi' do
      expect(@api_instance).to be_instance_of(F::CustomResourcesValueApi)
    end
  end

  # unit tests for custom_resources_values_get
  # Reads all Values
  # Reads all Values
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :ids Values identifiers
  # @option opts [Array<String>] :employee_ids Employee identifiers
  # @return [CustomResourcesValuesGet200Response]
  describe 'custom_resources_values_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for custom_resources_values_id_get
  # Reads a single Value
  # Reads a single Value
  # @param id Values identifiers
  # @param [Hash] opts the optional parameters
  # @return [CustomResourcesValue]
  describe 'custom_resources_values_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for custom_resources_values_post
  # Creates a Value
  # Creates a Value
  # @param [Hash] opts the optional parameters
  # @option opts [CustomResourcesValuesPostRequest] :custom_resources_values_post_request 
  # @return [CustomResourcesValue]
  describe 'custom_resources_values_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
