=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-10-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for F::Api::ExpensesMileageApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExpensesMileageApi' do
  before do
    # run before each test
    @api_instance = F::Api::ExpensesMileageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExpensesMileageApi' do
    it 'should create an instance of ExpensesMileageApi' do
      expect(@api_instance).to be_instance_of(F::Api::ExpensesMileageApi)
    end
  end

  # unit tests for expenses_mileages_get
  # Reads all Mileages
  # Reads all Mileages
  # @param include_manual_drafts 
  # @param include_attachments 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :ids Return only the mileage records with these ids.
  # @option opts [Array<String>] :expenses_expensable_ids Return only the mileage records attached to these expensables. A mileage record is the detail record of an expensable, so this is the usual way to reach it from the header.
  # @option opts [Array<String>] :employee_ids Return only the mileage records of these employees.
  # @option opts [Array<String>] :external_authorization_ids 
  # @option opts [Array<String>] :card_ids Return only the mileage records paid with these cards.
  # @option opts [Array<String>] :card_payment_ids Return only the mileage records raised from these card payments.
  # @option opts [String] :from Start of the window of travel dates (&#x60;effective_on&#x60;) to return, inclusive. It only takes effect together with &#x60;to&#x60;: given on its own it is ignored.
  # @option opts [String] :to End of the window of travel dates (&#x60;effective_on&#x60;) to return, exclusive. It only takes effect together with &#x60;from&#x60;.
  # @option opts [Array<String>] :dispute_ids Return only the mileage records under these payment disputes.
  # @return [ExpensesMileagesGet200Response]
  describe 'expenses_mileages_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for expenses_mileages_id_get
  # Reads a single Mileage
  # Reads a single Mileage
  # @param id Return only the mileage records with these ids.
  # @param [Hash] opts the optional parameters
  # @return [ExpensesMileage]
  describe 'expenses_mileages_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
