=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for F::Api::FinanceAccountApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FinanceAccountApi' do
  before do
    # run before each test
    @api_instance = F::Api::FinanceAccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FinanceAccountApi' do
    it 'should create an instance of FinanceAccountApi' do
      expect(@api_instance).to be_instance_of(F::Api::FinanceAccountApi)
    end
  end

  # unit tests for finance_accounts_get
  # Reads all Accounts
  # Fetch one or all ledger accounts for the company legal_entities.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :ids Search ledger accounts by ID
  # @option opts [Array<String>] :legal_entity_ids Search ledger accounts by legal_entity_id
  # @option opts [Array<String>] :types Search ledger accounts by type
  # @option opts [String] :number Search ledger accounts by number
  # @option opts [String] :updated_from Start date for filtering ledger accounts based on their last update.
  # @return [FinanceAccountsGet200Response]
  describe 'finance_accounts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for finance_accounts_id_get
  # Reads a single Account
  # Fetch one or all ledger accounts for the company legal_entities.
  # @param id Search ledger accounts by ID
  # @param [Hash] opts the optional parameters
  # @return [FinanceAccount]
  describe 'finance_accounts_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for finance_accounts_id_put
  # Updates an Account
  # Update a ledger account.
  # @param id Unique identifier in factorial for the ledger account
  # @param [Hash] opts the optional parameters
  # @option opts [FinanceAccountsIdPutRequest] :finance_accounts_id_put_request 
  # @return [FinanceAccount]
  describe 'finance_accounts_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for finance_accounts_post
  # Creates an Account
  # Create a ledger account for the company legal_entity. To avoid duplicates use the external_id field to set the ID of the ledger account in the external system.
  # @param [Hash] opts the optional parameters
  # @option opts [FinanceAccountsPostRequest] :finance_accounts_post_request 
  # @return [FinanceAccount]
  describe 'finance_accounts_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
