=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for F::LocationsLocationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LocationsLocationApi' do
  before do
    # run before each test
    @api_instance = F::LocationsLocationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LocationsLocationApi' do
    it 'should create an instance of LocationsLocationApi' do
      expect(@api_instance).to be_instance_of(F::LocationsLocationApi)
    end
  end

  # unit tests for locations_locations_get
  # Reads all Locations
  # Reads all Locations
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :ids The location IDs to filter the results.
  # @option opts [Array<String>] :employee_ids Return only the locations assigned to these employees.
  # @option opts [Boolean] :main Wether to filter only the main location.
  # @return [LocationsLocationsGet200Response]
  describe 'locations_locations_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for locations_locations_id_delete
  # Deletes a Location
  # Deletes a Location
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [LocationsLocation]
  describe 'locations_locations_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for locations_locations_id_get
  # Reads a single Location
  # Reads a single Location
  # @param id The location IDs to filter the results.
  # @param [Hash] opts the optional parameters
  # @return [LocationsLocation]
  describe 'locations_locations_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for locations_locations_id_put
  # Updates a Location
  # Updates a Location
  # @param id identifier of the location
  # @param [Hash] opts the optional parameters
  # @option opts [LocationsLocationsIdPutRequest] :locations_locations_id_put_request 
  # @return [LocationsLocation]
  describe 'locations_locations_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for locations_locations_post
  # Creates a Location
  # Creates a Location
  # @param [Hash] opts the optional parameters
  # @option opts [LocationsLocationsPostRequest] :locations_locations_post_request 
  # @return [LocationsLocation]
  describe 'locations_locations_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
