=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for F::PayrollIntegrationsBaseCodeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PayrollIntegrationsBaseCodeApi' do
  before do
    # run before each test
    @api_instance = F::PayrollIntegrationsBaseCodeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PayrollIntegrationsBaseCodeApi' do
    it 'should create an instance of PayrollIntegrationsBaseCodeApi' do
      expect(@api_instance).to be_instance_of(F::PayrollIntegrationsBaseCodeApi)
    end
  end

  # unit tests for payroll_integrations_base_codes_get
  # Reads all Codes
  # Reads all Codes
  # @param integrations Payroll Integration names
  # @param [Hash] opts the optional parameters
  # @option opts [String] :code Code Value
  # @option opts [String] :codeable_id Related object ID. Used together with codeable_type
  # @option opts [String] :codeable_type Related object type. Used together with codeable_id
  # @return [PayrollIntegrationsBaseCodesGet200Response]
  describe 'payroll_integrations_base_codes_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for payroll_integrations_base_codes_id_delete
  # Deletes a Code
  # Deletes a Code
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [PayrollIntegrationsBaseCode]
  describe 'payroll_integrations_base_codes_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for payroll_integrations_base_codes_id_put
  # Updates a Code
  # Updates a Code
  # @param id Code identifier
  # @param [Hash] opts the optional parameters
  # @option opts [PayrollIntegrationsBaseCodesIdPutRequest] :payroll_integrations_base_codes_id_put_request 
  # @return [PayrollIntegrationsBaseCode]
  describe 'payroll_integrations_base_codes_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for payroll_integrations_base_codes_post
  # Creates a Code
  # Creates a Code
  # @param [Hash] opts the optional parameters
  # @option opts [PayrollIntegrationsBaseCodesPostRequest] :payroll_integrations_base_codes_post_request 
  # @return [PayrollIntegrationsBaseCode]
  describe 'payroll_integrations_base_codes_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
