=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-10-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for F::Api::ProcurementPoLineItemApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProcurementPoLineItemApi' do
  before do
    # run before each test
    @api_instance = F::Api::ProcurementPoLineItemApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProcurementPoLineItemApi' do
    it 'should create an instance of ProcurementPoLineItemApi' do
      expect(@api_instance).to be_instance_of(F::Api::ProcurementPoLineItemApi)
    end
  end

  # unit tests for procurement_po_line_items_get
  # Reads all Po line items
  # Fetch line items for a purchase order.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :ids An array of line item IDs to filter by.
  # @option opts [Array<String>] :purchase_order_ids An array of purchase order IDs to filter line items for.
  # @return [ProcurementPoLineItemsGet200Response]
  describe 'procurement_po_line_items_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for procurement_po_line_items_id_get
  # Reads a single Po line item
  # Fetch line items for a purchase order.
  # @param id An array of line item IDs to filter by.
  # @param [Hash] opts the optional parameters
  # @return [ProcurementPoLineItem]
  describe 'procurement_po_line_items_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
