=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-10-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for F::Api::TeamsMembershipApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TeamsMembershipApi' do
  before do
    # run before each test
    @api_instance = F::Api::TeamsMembershipApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TeamsMembershipApi' do
    it 'should create an instance of TeamsMembershipApi' do
      expect(@api_instance).to be_instance_of(F::Api::TeamsMembershipApi)
    end
  end

  # unit tests for teams_memberships_get
  # Reads all Memberships
  # Get all memberships.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :ids Return only the memberships with these ids.
  # @option opts [Boolean] :lead Whether the employee is a lead of the team or not
  # @option opts [Array<String>] :team_ids Return only the memberships of these teams.
  # @option opts [Array<String>] :employee_ids Return only the memberships of these employees.
  # @option opts [Boolean] :with_source_attribution Populate &#x60;direct&#x60;, &#x60;source_team_ids&#x60; and &#x60;parent_team_ids&#x60; on each returned membership (nested teams). Only honoured when filtering by a single &#x60;employee_ids&#x60; value without &#x60;team_ids&#x60; — the read that attributes one employee&#39;s own memberships, and the only one that resolves &#x60;direct&#x60;. Reads filtered by a single team already return &#x60;source_team_ids&#x60;/&#x60;parent_team_ids&#x60; without this flag (&#x60;direct&#x60; stays null there); bulk reads ignore it entirely. Unsupported filter combinations return &#x60;200&#x60; with empty attribution rather than an error. Attribution is resolved per employee and is significantly more expensive than a plain read: intended for per-profile lookups, not bulk synchronization.
  # @return [TeamsMembershipsGet200Response]
  describe 'teams_memberships_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for teams_memberships_id_delete
  # Deletes a Membership
  # Delete the membership to remove the employee from the team. For companies with nested teams what actually gets deleted depends on the kind of row: deleting a direct membership removes it, and the inherited copies it produced in the ancestor teams are cleaned up asynchronously. Deleting an INHERITED membership instead removes the employee&#39;s direct membership in EVERY sub-team that row originates from — rows with other ids, in teams you did not name — and the request is rejected altogether if you cannot manage one of those sub-teams. The inherited row you named also disappears asynchronously rather than in the request, so an immediate re-read may still return it; repeating the DELETE is safe rather than an error. Read that employee&#39;s memberships with &#x60;with_source_attribution&#x60; before deleting to see what is at stake: &#x60;direct&#x60; indicates which kind of row it is, and &#x60;source_team_ids&#x60; where the deletion would land. Both are advisory — the read and the delete resolve their answers independently, so re-read after deleting rather than assuming which branch ran.
  # @param id Membership id.
  # @param [Hash] opts the optional parameters
  # @return [TeamsMembership]
  describe 'teams_memberships_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for teams_memberships_id_get
  # Reads a single Membership
  # Get all memberships.
  # @param id Return only the memberships with these ids.
  # @param [Hash] opts the optional parameters
  # @return [TeamsMembership]
  describe 'teams_memberships_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for teams_memberships_id_put
  # Updates a Membership
  # Update the membership to either make the employee a lead of the team or remove them as a lead. For companies with nested teams, promoting an inherited membership (&#x60;lead: true&#x60;) first converts the employee into a direct member of the team (leads must be direct members), so the row becomes direct as a side effect. Demoting (&#x60;lead: false&#x60;) only removes the lead flag and keeps the membership.
  # @param id Membership id.
  # @param [Hash] opts the optional parameters
  # @option opts [TeamsMembershipsIdPutRequest] :teams_memberships_id_put_request 
  # @return [TeamsMembership]
  describe 'teams_memberships_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for teams_memberships_move_post
  # Moves a Membership
  # Move a membership to a different team in one operation (the employee is removed from the current team and added to the destination). Requires the nested teams feature and permission to manage both teams. Only direct memberships can be moved — moving an inherited row is rejected.
  # @param [Hash] opts the optional parameters
  # @option opts [TeamsMembershipsMovePostRequest] :teams_memberships_move_post_request 
  # @return [TeamsMembership]
  describe 'teams_memberships_move_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for teams_memberships_post
  # Creates a Membership
  # Assign an employee to a team, meaning create a membership. For companies with nested teams, two extra semantics apply. Propagation: memberships are inherited upwards, so after adding an employee to a sub-team, inherited membership rows for its ancestor teams are materialized asynchronously — rows you did not create will appear in later reads. Reuse: if the employee already has a membership row on that team (typically an inherited one), no new row is created — the employee becomes a direct member of the team, the &#x60;lead&#x60; flag is applied when you send one, and the existing row (with its existing id) is returned instead of a new resource. Omitting &#x60;lead&#x60; leaves a reused row&#39;s leadership as it was, so replaying an addition never demotes a current lead; a genuinely new row is created without it. The response is still &#x60;201&#x60; when an existing row is reused, so compare the returned &#x60;id&#x60; against what you already hold to tell the two cases apart.
  # @param [Hash] opts the optional parameters
  # @option opts [TeamsMembershipsPostRequest] :teams_memberships_post_request 
  # @return [TeamsMembership]
  describe 'teams_memberships_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
