=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for F::Api::TimeoffPolicyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TimeoffPolicyApi' do
  before do
    # run before each test
    @api_instance = F::Api::TimeoffPolicyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimeoffPolicyApi' do
    it 'should create an instance of TimeoffPolicyApi' do
      expect(@api_instance).to be_instance_of(F::Api::TimeoffPolicyApi)
    end
  end

  # unit tests for timeoff_policies_get
  # Reads all Policies
  # Reads all Policies
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :ids The policies ids to retrieve.
  # @option opts [Array<String>] :company_ids The company ids to retrieve policies.
  # @return [TimeoffPoliciesGet200Response]
  describe 'timeoff_policies_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for timeoff_policies_id_delete
  # Deletes a Policy
  # Deletes a Policy
  # @param id Id of the policy to delete.
  # @param [Hash] opts the optional parameters
  # @return [TimeoffPolicy]
  describe 'timeoff_policies_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for timeoff_policies_id_get
  # Reads a single Policy
  # Reads a single Policy
  # @param id The policies ids to retrieve.
  # @param [Hash] opts the optional parameters
  # @return [TimeoffPolicy]
  describe 'timeoff_policies_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for timeoff_policies_id_put
  # Updates a Policy
  # Updates a Policy
  # @param id Id of the policy to update.
  # @param [Hash] opts the optional parameters
  # @option opts [TimeoffPoliciesIdPutRequest] :timeoff_policies_id_put_request 
  # @return [TimeoffPolicy]
  describe 'timeoff_policies_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for timeoff_policies_post
  # Creates a Policy
  # Creates a Policy
  # @param [Hash] opts the optional parameters
  # @option opts [TimeoffPoliciesPostRequest] :timeoff_policies_post_request 
  # @return [TimeoffPolicy]
  describe 'timeoff_policies_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
