=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for F::Api::TrainingsTrainingMembershipApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TrainingsTrainingMembershipApi' do
  before do
    # run before each test
    @api_instance = F::Api::TrainingsTrainingMembershipApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TrainingsTrainingMembershipApi' do
    it 'should create an instance of TrainingsTrainingMembershipApi' do
      expect(@api_instance).to be_instance_of(F::Api::TrainingsTrainingMembershipApi)
    end
  end

  # unit tests for trainings_training_memberships_bulk_create_post
  # Bulk creates a Training membership
  # Creates training memberships in bulk
  # @param [Hash] opts the optional parameters
  # @option opts [TrainingsTrainingMembershipsBulkCreatePostRequest] :trainings_training_memberships_bulk_create_post_request 
  # @return [Array<TrainingsTrainingMembership>]
  describe 'trainings_training_memberships_bulk_create_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for trainings_training_memberships_bulk_destroy_post
  # Bulk destroys a Training membership
  # Deletes training memberships in bulk
  # @param [Hash] opts the optional parameters
  # @option opts [TrainingsTrainingMembershipsBulkDestroyPostRequest] :trainings_training_memberships_bulk_destroy_post_request 
  # @return [Array<TrainingsTrainingMembership>]
  describe 'trainings_training_memberships_bulk_destroy_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for trainings_training_memberships_get
  # Reads all Training memberships
  # Reads all Training memberships
  # @param due_date This field is used to filter training memberships by due date. Values can be &#39;overdue&#39;, &#39;no_due_date&#39;, or a number of days (e.g., &#39;7&#39;, &#39;30&#39;, &#39;90&#39;).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :training_id This field is used to filter those trainings memberships that belongs to this training.
  # @option opts [Array<String>] :ids This field is used to filter those trainings memberships whose id match with the given.
  # @option opts [String] :search This field is used to filter those trainings memberships whose employee name include some of the text written.
  # @option opts [String] :team_id This field is used to filter those memberships whose employees belongs to this team.
  # @option opts [String] :status This field is used to filter those trainings memberships whose attendance status is the given.
  # @option opts [String] :class_id This field is used to filter those trainings memberships whose employees belongs to this group.
  # @option opts [String] :employee_id Get the training memberships by passing the employee id
  # @return [TrainingsTrainingMembershipsGet200Response]
  describe 'trainings_training_memberships_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for trainings_training_memberships_id_get
  # Reads a single Training membership
  # Reads a single Training membership
  # @param id This field is used to filter those trainings memberships whose id match with the given.
  # @param [Hash] opts the optional parameters
  # @return [TrainingsTrainingMembership]
  describe 'trainings_training_memberships_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for trainings_training_memberships_id_put
  # Updates a Training membership
  # Update a training membership
  # @param id Unique identifier for the training membership. Only used to identify the training membership to update.
  # @param [Hash] opts the optional parameters
  # @option opts [TrainingsTrainingMembershipsIdPutRequest] :trainings_training_memberships_id_put_request 
  # @return [TrainingsTrainingMembership]
  describe 'trainings_training_memberships_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
