=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F
  class AtsAnswersPostRequest < ApiModelBase
    # Identifier of the question
    attr_accessor :ats_question_id

    # Identifier of the application
    attr_accessor :ats_application_id

    # Value of the answer
    attr_accessor :value

    # Label of the question
    attr_accessor :original_question_label

    # Type of the question
    attr_accessor :original_question_type

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ats_question_id' => :'ats_question_id',
        :'ats_application_id' => :'ats_application_id',
        :'value' => :'value',
        :'original_question_label' => :'original_question_label',
        :'original_question_type' => :'original_question_type'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ats_question_id' => :'String',
        :'ats_application_id' => :'String',
        :'value' => :'String',
        :'original_question_label' => :'String',
        :'original_question_type' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::AtsAnswersPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::AtsAnswersPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ats_question_id')
        self.ats_question_id = attributes[:'ats_question_id']
      else
        self.ats_question_id = nil
      end

      if attributes.key?(:'ats_application_id')
        self.ats_application_id = attributes[:'ats_application_id']
      else
        self.ats_application_id = nil
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      else
        self.value = nil
      end

      if attributes.key?(:'original_question_label')
        self.original_question_label = attributes[:'original_question_label']
      else
        self.original_question_label = nil
      end

      if attributes.key?(:'original_question_type')
        self.original_question_type = attributes[:'original_question_type']
      else
        self.original_question_type = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @ats_question_id.nil?
        invalid_properties.push('invalid value for "ats_question_id", ats_question_id cannot be nil.')
      end

      if @ats_application_id.nil?
        invalid_properties.push('invalid value for "ats_application_id", ats_application_id cannot be nil.')
      end

      if @value.nil?
        invalid_properties.push('invalid value for "value", value cannot be nil.')
      end

      if @original_question_label.nil?
        invalid_properties.push('invalid value for "original_question_label", original_question_label cannot be nil.')
      end

      if @original_question_type.nil?
        invalid_properties.push('invalid value for "original_question_type", original_question_type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @ats_question_id.nil?
      return false if @ats_application_id.nil?
      return false if @value.nil?
      return false if @original_question_label.nil?
      return false if @original_question_type.nil?
      original_question_type_validator = EnumAttributeValidator.new('String', ["text", "long_text", "single_choice", "multiple_choice"])
      return false unless original_question_type_validator.valid?(@original_question_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] ats_question_id Value to be assigned
    def ats_question_id=(ats_question_id)
      if ats_question_id.nil?
        fail ArgumentError, 'ats_question_id cannot be nil'
      end

      @ats_question_id = ats_question_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ats_application_id Value to be assigned
    def ats_application_id=(ats_application_id)
      if ats_application_id.nil?
        fail ArgumentError, 'ats_application_id cannot be nil'
      end

      @ats_application_id = ats_application_id
    end

    # Custom attribute writer method with validation
    # @param [Object] value Value to be assigned
    def value=(value)
      if value.nil?
        fail ArgumentError, 'value cannot be nil'
      end

      @value = value
    end

    # Custom attribute writer method with validation
    # @param [Object] original_question_label Value to be assigned
    def original_question_label=(original_question_label)
      if original_question_label.nil?
        fail ArgumentError, 'original_question_label cannot be nil'
      end

      @original_question_label = original_question_label
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] original_question_type Object to be assigned
    def original_question_type=(original_question_type)
      validator = EnumAttributeValidator.new('String', ["text", "long_text", "single_choice", "multiple_choice"])
      unless validator.valid?(original_question_type)
        fail ArgumentError, "invalid value for \"original_question_type\", must be one of #{validator.allowable_values}."
      end
      @original_question_type = original_question_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ats_question_id == o.ats_question_id &&
          ats_application_id == o.ats_application_id &&
          value == o.value &&
          original_question_label == o.original_question_label &&
          original_question_type == o.original_question_type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ats_question_id, ats_application_id, value, original_question_label, original_question_type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
