=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-10-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F::Api
  class ContractsMaterializedTemplateTemplateInner < ApiModelBase
    attr_accessor :id

    attr_accessor :field_id

    attr_accessor :label

    attr_accessor :field_type

    attr_accessor :edit_mode

    attr_accessor :source_level

    attr_accessor :options

    attr_accessor :dependencies

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'field_id' => :'field_id',
        :'label' => :'label',
        :'field_type' => :'field_type',
        :'edit_mode' => :'edit_mode',
        :'source_level' => :'source_level',
        :'options' => :'options',
        :'dependencies' => :'dependencies'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'field_id' => :'String',
        :'label' => :'String',
        :'field_type' => :'String',
        :'edit_mode' => :'String',
        :'source_level' => :'String',
        :'options' => :'Array<ContractsMaterializedTemplateTemplateInnerOptionsInner>',
        :'dependencies' => :'Array<ContractsMaterializedTemplateTemplateInnerDependenciesInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::Api::ContractsMaterializedTemplateTemplateInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::Api::ContractsMaterializedTemplateTemplateInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'field_id')
        self.field_id = attributes[:'field_id']
      else
        self.field_id = nil
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      else
        self.label = nil
      end

      if attributes.key?(:'field_type')
        self.field_type = attributes[:'field_type']
      else
        self.field_type = nil
      end

      if attributes.key?(:'edit_mode')
        self.edit_mode = attributes[:'edit_mode']
      else
        self.edit_mode = nil
      end

      if attributes.key?(:'source_level')
        self.source_level = attributes[:'source_level']
      end

      if attributes.key?(:'options')
        if (value = attributes[:'options']).is_a?(Array)
          self.options = value
        end
      end

      if attributes.key?(:'dependencies')
        if (value = attributes[:'dependencies']).is_a?(Array)
          self.dependencies = value
        end
      else
        self.dependencies = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @field_id.nil?
        invalid_properties.push('invalid value for "field_id", field_id cannot be nil.')
      end

      if @label.nil?
        invalid_properties.push('invalid value for "label", label cannot be nil.')
      end

      if @field_type.nil?
        invalid_properties.push('invalid value for "field_type", field_type cannot be nil.')
      end

      if @edit_mode.nil?
        invalid_properties.push('invalid value for "edit_mode", edit_mode cannot be nil.')
      end

      if @dependencies.nil?
        invalid_properties.push('invalid value for "dependencies", dependencies cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @field_id.nil?
      return false if @label.nil?
      return false if @field_type.nil?
      field_type_validator = EnumAttributeValidator.new('String', ["boolean", "cents", "integer", "option", "string"])
      return false unless field_type_validator.valid?(@field_type)
      return false if @edit_mode.nil?
      edit_mode_validator = EnumAttributeValidator.new('String', ["not_editable", "add_only", "full_editable"])
      return false unless edit_mode_validator.valid?(@edit_mode)
      source_level_validator = EnumAttributeValidator.new('String', ["company", "country", "legal_entity"])
      return false unless source_level_validator.valid?(@source_level)
      return false if @dependencies.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        @id = nil
        return
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] field_id Value to be assigned
    def field_id=(field_id)
      if field_id.nil?
        @field_id = nil
        return
      end

      @field_id = field_id
    end

    # Custom attribute writer method with validation
    # @param [Object] label Value to be assigned
    def label=(label)
      if label.nil?
        @label = nil
        return
      end

      @label = label
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] field_type Object to be assigned
    def field_type=(field_type)
      validator = EnumAttributeValidator.new('String', ["boolean", "cents", "integer", "option", "string"])
      unless validator.valid?(field_type)
        fail ArgumentError, "invalid value for \"field_type\", must be one of #{validator.allowable_values}."
      end
      @field_type = field_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] edit_mode Object to be assigned
    def edit_mode=(edit_mode)
      validator = EnumAttributeValidator.new('String', ["not_editable", "add_only", "full_editable"])
      unless validator.valid?(edit_mode)
        fail ArgumentError, "invalid value for \"edit_mode\", must be one of #{validator.allowable_values}."
      end
      @edit_mode = edit_mode
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] source_level Object to be assigned
    def source_level=(source_level)
      validator = EnumAttributeValidator.new('String', ["company", "country", "legal_entity"])
      unless validator.valid?(source_level)
        fail ArgumentError, "invalid value for \"source_level\", must be one of #{validator.allowable_values}."
      end
      @source_level = source_level
    end

    # Custom attribute writer method with validation
    # @param [Object] dependencies Value to be assigned
    def dependencies=(dependencies)
      if dependencies.nil?
        @dependencies = nil
        return
      end

      @dependencies = dependencies
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          field_id == o.field_id &&
          label == o.label &&
          field_type == o.field_type &&
          edit_mode == o.edit_mode &&
          source_level == o.source_level &&
          options == o.options &&
          dependencies == o.dependencies
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, field_id, label, field_type, edit_mode, source_level, options, dependencies].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
