=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-10-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F::Api
  class ContractsContractActivityPeriod < ApiModelBase
    # Identifier of the period, built from the contract id and the period start date. Periods are derived rather than stored, so this id is stable only while the underlying contract versions do not change.
    attr_accessor :id

    # ID of the contract this period belongs to.
    attr_accessor :contract_id

    # ID of the employee who holds the contract.
    attr_accessor :employee_id

    # Whether the employee is working during this period (activity) or not (inactivity). Only discontinuous contracts produce inactivity periods.
    attr_accessor :type

    # First day of the period.
    attr_accessor :activity_period_starts_on

    # Last day of the period, or null when the period is still open ended.
    attr_accessor :activity_period_ends_on

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'contract_id' => :'contract_id',
        :'employee_id' => :'employee_id',
        :'type' => :'type',
        :'activity_period_starts_on' => :'activity_period_starts_on',
        :'activity_period_ends_on' => :'activity_period_ends_on'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'contract_id' => :'String',
        :'employee_id' => :'String',
        :'type' => :'String',
        :'activity_period_starts_on' => :'String',
        :'activity_period_ends_on' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::Api::ContractsContractActivityPeriod` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::Api::ContractsContractActivityPeriod`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'contract_id')
        self.contract_id = attributes[:'contract_id']
      else
        self.contract_id = nil
      end

      if attributes.key?(:'employee_id')
        self.employee_id = attributes[:'employee_id']
      else
        self.employee_id = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'activity_period_starts_on')
        self.activity_period_starts_on = attributes[:'activity_period_starts_on']
      else
        self.activity_period_starts_on = nil
      end

      if attributes.key?(:'activity_period_ends_on')
        self.activity_period_ends_on = attributes[:'activity_period_ends_on']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @contract_id.nil?
        invalid_properties.push('invalid value for "contract_id", contract_id cannot be nil.')
      end

      if @employee_id.nil?
        invalid_properties.push('invalid value for "employee_id", employee_id cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @activity_period_starts_on.nil?
        invalid_properties.push('invalid value for "activity_period_starts_on", activity_period_starts_on cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @contract_id.nil?
      return false if @employee_id.nil?
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["activity", "inactivity"])
      return false unless type_validator.valid?(@type)
      return false if @activity_period_starts_on.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        @id = nil
        return
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] contract_id Value to be assigned
    def contract_id=(contract_id)
      if contract_id.nil?
        @contract_id = nil
        return
      end

      @contract_id = contract_id
    end

    # Custom attribute writer method with validation
    # @param [Object] employee_id Value to be assigned
    def employee_id=(employee_id)
      if employee_id.nil?
        @employee_id = nil
        return
      end

      @employee_id = employee_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["activity", "inactivity"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] activity_period_starts_on Value to be assigned
    def activity_period_starts_on=(activity_period_starts_on)
      if activity_period_starts_on.nil?
        @activity_period_starts_on = nil
        return
      end

      @activity_period_starts_on = activity_period_starts_on
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          contract_id == o.contract_id &&
          employee_id == o.employee_id &&
          type == o.type &&
          activity_period_starts_on == o.activity_period_starts_on &&
          activity_period_ends_on == o.activity_period_ends_on
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, contract_id, employee_id, type, activity_period_starts_on, activity_period_ends_on].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
