=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F
  class CustomFieldsFieldsPostRequest < ApiModelBase
    # Company identifier where this field belongs
    attr_accessor :company_id

    # Group of employees that can edit the field
    attr_accessor :editable

    # Group of employees that can see the field
    attr_accessor :visible

    # Field label
    attr_accessor :label

    attr_accessor :field_type

    # Minimum value in range field type
    attr_accessor :min_value

    # Maximum value in range field type
    attr_accessor :max_value

    # Requirement to fill this field
    attr_accessor :required

    # Array of options
    attr_accessor :options

    attr_accessor :position

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'company_id' => :'company_id',
        :'editable' => :'editable',
        :'visible' => :'visible',
        :'label' => :'label',
        :'field_type' => :'field_type',
        :'min_value' => :'min_value',
        :'max_value' => :'max_value',
        :'required' => :'required',
        :'options' => :'options',
        :'position' => :'position'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'company_id' => :'String',
        :'editable' => :'String',
        :'visible' => :'String',
        :'label' => :'String',
        :'field_type' => :'String',
        :'min_value' => :'Integer',
        :'max_value' => :'Integer',
        :'required' => :'Boolean',
        :'options' => :'Array<String>',
        :'position' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::CustomFieldsFieldsPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::CustomFieldsFieldsPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      else
        self.company_id = nil
      end

      if attributes.key?(:'editable')
        self.editable = attributes[:'editable']
      end

      if attributes.key?(:'visible')
        self.visible = attributes[:'visible']
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      end

      if attributes.key?(:'field_type')
        self.field_type = attributes[:'field_type']
      else
        self.field_type = nil
      end

      if attributes.key?(:'min_value')
        self.min_value = attributes[:'min_value']
      end

      if attributes.key?(:'max_value')
        self.max_value = attributes[:'max_value']
      end

      if attributes.key?(:'required')
        self.required = attributes[:'required']
      end

      if attributes.key?(:'options')
        if (value = attributes[:'options']).is_a?(Array)
          self.options = value
        end
      end

      if attributes.key?(:'position')
        self.position = attributes[:'position']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @company_id.nil?
        invalid_properties.push('invalid value for "company_id", company_id cannot be nil.')
      end

      if @field_type.nil?
        invalid_properties.push('invalid value for "field_type", field_type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @company_id.nil?
      editable_validator = EnumAttributeValidator.new('String', ["owned", "reportees", "team_leader", "legal_entity", "everybody"])
      return false unless editable_validator.valid?(@editable)
      visible_validator = EnumAttributeValidator.new('String', ["owned", "reportees", "team_leader", "legal_entity", "everybody"])
      return false unless visible_validator.valid?(@visible)
      return false if @field_type.nil?
      field_type_validator = EnumAttributeValidator.new('String', ["text", "long_text", "date", "rating", "checkbox", "single_choice", "multiple_choice", "money", "cents"])
      return false unless field_type_validator.valid?(@field_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] company_id Value to be assigned
    def company_id=(company_id)
      if company_id.nil?
        @company_id = nil
        return
      end

      @company_id = company_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] editable Object to be assigned
    def editable=(editable)
      validator = EnumAttributeValidator.new('String', ["owned", "reportees", "team_leader", "legal_entity", "everybody"])
      unless validator.valid?(editable)
        fail ArgumentError, "invalid value for \"editable\", must be one of #{validator.allowable_values}."
      end
      @editable = editable
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] visible Object to be assigned
    def visible=(visible)
      validator = EnumAttributeValidator.new('String', ["owned", "reportees", "team_leader", "legal_entity", "everybody"])
      unless validator.valid?(visible)
        fail ArgumentError, "invalid value for \"visible\", must be one of #{validator.allowable_values}."
      end
      @visible = visible
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] field_type Object to be assigned
    def field_type=(field_type)
      validator = EnumAttributeValidator.new('String', ["text", "long_text", "date", "rating", "checkbox", "single_choice", "multiple_choice", "money", "cents"])
      unless validator.valid?(field_type)
        fail ArgumentError, "invalid value for \"field_type\", must be one of #{validator.allowable_values}."
      end
      @field_type = field_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          company_id == o.company_id &&
          editable == o.editable &&
          visible == o.visible &&
          label == o.label &&
          field_type == o.field_type &&
          min_value == o.min_value &&
          max_value == o.max_value &&
          required == o.required &&
          options == o.options &&
          position == o.position
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [company_id, editable, visible, label, field_type, min_value, max_value, required, options, position].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
