=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F::Api
  class EmployeesEmployee < ApiModelBase
    # id of the employee.
    attr_accessor :id

    # access_id associated to the employee.
    attr_accessor :access_id

    # name of the employee.
    attr_accessor :first_name

    # last name of the employee.
    attr_accessor :last_name

    # full name of the employee.
    attr_accessor :full_name

    # nickname of the employee or a name that defines the employee better.
    attr_accessor :preferred_name

    # Birthname of the employee.
    attr_accessor :birth_name

    # gender of the employee (male | female).
    attr_accessor :gender

    # national identifier number.
    attr_accessor :identifier

    # type of identifier (ex passport).
    attr_accessor :identifier_type

    # personal email of the employee.
    attr_accessor :email

    # email associated to the session.
    attr_accessor :login_email

    # birthday of the employee.
    attr_accessor :birthday_on

    # nationality country code of the employee (Spain ES, United Kingdom GB).
    attr_accessor :nationality

    # address of the employee.
    attr_accessor :address_line_1

    # secondary address of the employee.
    attr_accessor :address_line_2

    # postal code of the employee.
    attr_accessor :postal_code

    # city of the employee.
    attr_accessor :city

    # state/province/region of the employee.
    attr_accessor :state

    # country code of the employee (Spain ES, United Kingdom GB).
    attr_accessor :country

    # bank account number of the employee.
    attr_accessor :bank_number

    # code to identify banks and financial institutions globally.
    attr_accessor :swift_bic

    # bank number format.
    attr_accessor :bank_number_format

    # id of the company to which the employee belongs (not editable).
    attr_accessor :company_id

    # legal entity of the employee, references to companies/legal_entities.
    attr_accessor :legal_entity_id

    # location id of the employee, references to locations/locations.
    attr_accessor :location_id

    # Default work area ID for the employee at the default workplace. References locations/work_areas.
    attr_accessor :default_work_area_id

    # creation date of the employee.
    attr_accessor :created_at

    # date of last modification of the employee
    attr_accessor :updated_at

    # social security number of the employee.
    attr_accessor :social_security_number

    # is the employee being terminated?
    attr_accessor :is_terminating

    # termination date of the employee.
    attr_accessor :terminated_on

    # termination reason type of the employee
    attr_accessor :termination_reason_type

    # A reason for the termination.
    attr_accessor :termination_reason

    # observations about the termination.
    attr_accessor :termination_observations

    # manager id of the employee, you can get the manager id from employees endpoint.
    attr_accessor :manager_id

    # Timeoff manager id of the employee.
    attr_accessor :timeoff_manager_id

    # phone number of the employee.
    attr_accessor :phone_number

    # identity number or string used inside a company to internally identify the employee.
    attr_accessor :company_identifier

    # age of the employee.
    attr_accessor :age_number

    # The description of the termination type.
    attr_accessor :termination_type_description

    # name of the employee contact.
    attr_accessor :contact_name

    # phone number of the employee contact .
    attr_accessor :contact_number

    # personal email of the employee.
    attr_accessor :personal_email

    # date since when the employee is working in the company.
    attr_accessor :seniority_calculation_date

    # Confirmed email address for company communications and notifications. Separate from login email, used for internal company announcements.
    attr_accessor :communications_email

    # unconfirmed communications email address for the employee.
    attr_accessor :unconfirmed_communications_email

    # pronouns that an employee uses to define themselves.
    attr_accessor :pronouns

    # status of the employee, true when active, false when terminated.
    attr_accessor :active

    # officially certified level of disability granted by public administration for individuals with physical or mental impairments, expressed in cents
    attr_accessor :disability_percentage_cents

    # identifier expiration date
    attr_accessor :identifier_expiration_date

    # employee included in a time tracking policy.
    attr_accessor :attendable

    # Country of birth of the employee.
    attr_accessor :country_of_birth

    # Birthplace of the employee.
    attr_accessor :birthplace

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'access_id' => :'access_id',
        :'first_name' => :'first_name',
        :'last_name' => :'last_name',
        :'full_name' => :'full_name',
        :'preferred_name' => :'preferred_name',
        :'birth_name' => :'birth_name',
        :'gender' => :'gender',
        :'identifier' => :'identifier',
        :'identifier_type' => :'identifier_type',
        :'email' => :'email',
        :'login_email' => :'login_email',
        :'birthday_on' => :'birthday_on',
        :'nationality' => :'nationality',
        :'address_line_1' => :'address_line_1',
        :'address_line_2' => :'address_line_2',
        :'postal_code' => :'postal_code',
        :'city' => :'city',
        :'state' => :'state',
        :'country' => :'country',
        :'bank_number' => :'bank_number',
        :'swift_bic' => :'swift_bic',
        :'bank_number_format' => :'bank_number_format',
        :'company_id' => :'company_id',
        :'legal_entity_id' => :'legal_entity_id',
        :'location_id' => :'location_id',
        :'default_work_area_id' => :'default_work_area_id',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'social_security_number' => :'social_security_number',
        :'is_terminating' => :'is_terminating',
        :'terminated_on' => :'terminated_on',
        :'termination_reason_type' => :'termination_reason_type',
        :'termination_reason' => :'termination_reason',
        :'termination_observations' => :'termination_observations',
        :'manager_id' => :'manager_id',
        :'timeoff_manager_id' => :'timeoff_manager_id',
        :'phone_number' => :'phone_number',
        :'company_identifier' => :'company_identifier',
        :'age_number' => :'age_number',
        :'termination_type_description' => :'termination_type_description',
        :'contact_name' => :'contact_name',
        :'contact_number' => :'contact_number',
        :'personal_email' => :'personal_email',
        :'seniority_calculation_date' => :'seniority_calculation_date',
        :'communications_email' => :'communications_email',
        :'unconfirmed_communications_email' => :'unconfirmed_communications_email',
        :'pronouns' => :'pronouns',
        :'active' => :'active',
        :'disability_percentage_cents' => :'disability_percentage_cents',
        :'identifier_expiration_date' => :'identifier_expiration_date',
        :'attendable' => :'attendable',
        :'country_of_birth' => :'country_of_birth',
        :'birthplace' => :'birthplace'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'access_id' => :'String',
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'full_name' => :'String',
        :'preferred_name' => :'String',
        :'birth_name' => :'String',
        :'gender' => :'String',
        :'identifier' => :'String',
        :'identifier_type' => :'String',
        :'email' => :'String',
        :'login_email' => :'String',
        :'birthday_on' => :'String',
        :'nationality' => :'String',
        :'address_line_1' => :'String',
        :'address_line_2' => :'String',
        :'postal_code' => :'String',
        :'city' => :'String',
        :'state' => :'String',
        :'country' => :'String',
        :'bank_number' => :'String',
        :'swift_bic' => :'String',
        :'bank_number_format' => :'String',
        :'company_id' => :'String',
        :'legal_entity_id' => :'String',
        :'location_id' => :'String',
        :'default_work_area_id' => :'String',
        :'created_at' => :'String',
        :'updated_at' => :'String',
        :'social_security_number' => :'String',
        :'is_terminating' => :'Boolean',
        :'terminated_on' => :'String',
        :'termination_reason_type' => :'String',
        :'termination_reason' => :'String',
        :'termination_observations' => :'String',
        :'manager_id' => :'String',
        :'timeoff_manager_id' => :'String',
        :'phone_number' => :'String',
        :'company_identifier' => :'String',
        :'age_number' => :'Integer',
        :'termination_type_description' => :'String',
        :'contact_name' => :'String',
        :'contact_number' => :'String',
        :'personal_email' => :'String',
        :'seniority_calculation_date' => :'String',
        :'communications_email' => :'String',
        :'unconfirmed_communications_email' => :'String',
        :'pronouns' => :'String',
        :'active' => :'Boolean',
        :'disability_percentage_cents' => :'Integer',
        :'identifier_expiration_date' => :'String',
        :'attendable' => :'Boolean',
        :'country_of_birth' => :'String',
        :'birthplace' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::Api::EmployeesEmployee` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::Api::EmployeesEmployee`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'access_id')
        self.access_id = attributes[:'access_id']
      else
        self.access_id = nil
      end

      if attributes.key?(:'first_name')
        self.first_name = attributes[:'first_name']
      else
        self.first_name = nil
      end

      if attributes.key?(:'last_name')
        self.last_name = attributes[:'last_name']
      else
        self.last_name = nil
      end

      if attributes.key?(:'full_name')
        self.full_name = attributes[:'full_name']
      else
        self.full_name = nil
      end

      if attributes.key?(:'preferred_name')
        self.preferred_name = attributes[:'preferred_name']
      end

      if attributes.key?(:'birth_name')
        self.birth_name = attributes[:'birth_name']
      end

      if attributes.key?(:'gender')
        self.gender = attributes[:'gender']
      end

      if attributes.key?(:'identifier')
        self.identifier = attributes[:'identifier']
      end

      if attributes.key?(:'identifier_type')
        self.identifier_type = attributes[:'identifier_type']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'login_email')
        self.login_email = attributes[:'login_email']
      end

      if attributes.key?(:'birthday_on')
        self.birthday_on = attributes[:'birthday_on']
      end

      if attributes.key?(:'nationality')
        self.nationality = attributes[:'nationality']
      end

      if attributes.key?(:'address_line_1')
        self.address_line_1 = attributes[:'address_line_1']
      end

      if attributes.key?(:'address_line_2')
        self.address_line_2 = attributes[:'address_line_2']
      end

      if attributes.key?(:'postal_code')
        self.postal_code = attributes[:'postal_code']
      end

      if attributes.key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'bank_number')
        self.bank_number = attributes[:'bank_number']
      end

      if attributes.key?(:'swift_bic')
        self.swift_bic = attributes[:'swift_bic']
      end

      if attributes.key?(:'bank_number_format')
        self.bank_number_format = attributes[:'bank_number_format']
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      else
        self.company_id = nil
      end

      if attributes.key?(:'legal_entity_id')
        self.legal_entity_id = attributes[:'legal_entity_id']
      end

      if attributes.key?(:'location_id')
        self.location_id = attributes[:'location_id']
      else
        self.location_id = nil
      end

      if attributes.key?(:'default_work_area_id')
        self.default_work_area_id = attributes[:'default_work_area_id']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'social_security_number')
        self.social_security_number = attributes[:'social_security_number']
      end

      if attributes.key?(:'is_terminating')
        self.is_terminating = attributes[:'is_terminating']
      else
        self.is_terminating = nil
      end

      if attributes.key?(:'terminated_on')
        self.terminated_on = attributes[:'terminated_on']
      end

      if attributes.key?(:'termination_reason_type')
        self.termination_reason_type = attributes[:'termination_reason_type']
      end

      if attributes.key?(:'termination_reason')
        self.termination_reason = attributes[:'termination_reason']
      end

      if attributes.key?(:'termination_observations')
        self.termination_observations = attributes[:'termination_observations']
      end

      if attributes.key?(:'manager_id')
        self.manager_id = attributes[:'manager_id']
      end

      if attributes.key?(:'timeoff_manager_id')
        self.timeoff_manager_id = attributes[:'timeoff_manager_id']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'company_identifier')
        self.company_identifier = attributes[:'company_identifier']
      end

      if attributes.key?(:'age_number')
        self.age_number = attributes[:'age_number']
      end

      if attributes.key?(:'termination_type_description')
        self.termination_type_description = attributes[:'termination_type_description']
      end

      if attributes.key?(:'contact_name')
        self.contact_name = attributes[:'contact_name']
      end

      if attributes.key?(:'contact_number')
        self.contact_number = attributes[:'contact_number']
      end

      if attributes.key?(:'personal_email')
        self.personal_email = attributes[:'personal_email']
      end

      if attributes.key?(:'seniority_calculation_date')
        self.seniority_calculation_date = attributes[:'seniority_calculation_date']
      end

      if attributes.key?(:'communications_email')
        self.communications_email = attributes[:'communications_email']
      end

      if attributes.key?(:'unconfirmed_communications_email')
        self.unconfirmed_communications_email = attributes[:'unconfirmed_communications_email']
      end

      if attributes.key?(:'pronouns')
        self.pronouns = attributes[:'pronouns']
      end

      if attributes.key?(:'active')
        self.active = attributes[:'active']
      end

      if attributes.key?(:'disability_percentage_cents')
        self.disability_percentage_cents = attributes[:'disability_percentage_cents']
      end

      if attributes.key?(:'identifier_expiration_date')
        self.identifier_expiration_date = attributes[:'identifier_expiration_date']
      end

      if attributes.key?(:'attendable')
        self.attendable = attributes[:'attendable']
      else
        self.attendable = nil
      end

      if attributes.key?(:'country_of_birth')
        self.country_of_birth = attributes[:'country_of_birth']
      end

      if attributes.key?(:'birthplace')
        self.birthplace = attributes[:'birthplace']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @access_id.nil?
        invalid_properties.push('invalid value for "access_id", access_id cannot be nil.')
      end

      if @first_name.nil?
        invalid_properties.push('invalid value for "first_name", first_name cannot be nil.')
      end

      if @last_name.nil?
        invalid_properties.push('invalid value for "last_name", last_name cannot be nil.')
      end

      if @full_name.nil?
        invalid_properties.push('invalid value for "full_name", full_name cannot be nil.')
      end

      if @company_id.nil?
        invalid_properties.push('invalid value for "company_id", company_id cannot be nil.')
      end

      if @location_id.nil?
        invalid_properties.push('invalid value for "location_id", location_id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @is_terminating.nil?
        invalid_properties.push('invalid value for "is_terminating", is_terminating cannot be nil.')
      end

      if @attendable.nil?
        invalid_properties.push('invalid value for "attendable", attendable cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @access_id.nil?
      return false if @first_name.nil?
      return false if @last_name.nil?
      return false if @full_name.nil?
      bank_number_format_validator = EnumAttributeValidator.new('String', ["iban", "sort_code_and_account_number", "routing_number_and_account_number", "clabe", "other", "bank_name_and_account_number"])
      return false unless bank_number_format_validator.valid?(@bank_number_format)
      return false if @company_id.nil?
      return false if @location_id.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      return false if @is_terminating.nil?
      return false if @attendable.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        @id = nil
        return
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] access_id Value to be assigned
    def access_id=(access_id)
      if access_id.nil?
        @access_id = nil
        return
      end

      @access_id = access_id
    end

    # Custom attribute writer method with validation
    # @param [Object] first_name Value to be assigned
    def first_name=(first_name)
      if first_name.nil?
        @first_name = nil
        return
      end

      @first_name = first_name
    end

    # Custom attribute writer method with validation
    # @param [Object] last_name Value to be assigned
    def last_name=(last_name)
      if last_name.nil?
        @last_name = nil
        return
      end

      @last_name = last_name
    end

    # Custom attribute writer method with validation
    # @param [Object] full_name Value to be assigned
    def full_name=(full_name)
      if full_name.nil?
        @full_name = nil
        return
      end

      @full_name = full_name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] bank_number_format Object to be assigned
    def bank_number_format=(bank_number_format)
      validator = EnumAttributeValidator.new('String', ["iban", "sort_code_and_account_number", "routing_number_and_account_number", "clabe", "other", "bank_name_and_account_number"])
      unless validator.valid?(bank_number_format)
        fail ArgumentError, "invalid value for \"bank_number_format\", must be one of #{validator.allowable_values}."
      end
      @bank_number_format = bank_number_format
    end

    # Custom attribute writer method with validation
    # @param [Object] company_id Value to be assigned
    def company_id=(company_id)
      if company_id.nil?
        @company_id = nil
        return
      end

      @company_id = company_id
    end

    # Custom attribute writer method with validation
    # @param [Object] location_id Value to be assigned
    def location_id=(location_id)
      if location_id.nil?
        @location_id = nil
        return
      end

      @location_id = location_id
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        @created_at = nil
        return
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        @updated_at = nil
        return
      end

      @updated_at = updated_at
    end

    # Custom attribute writer method with validation
    # @param [Object] is_terminating Value to be assigned
    def is_terminating=(is_terminating)
      if is_terminating.nil?
        @is_terminating = nil
        return
      end

      @is_terminating = is_terminating
    end

    # Custom attribute writer method with validation
    # @param [Object] attendable Value to be assigned
    def attendable=(attendable)
      if attendable.nil?
        @attendable = nil
        return
      end

      @attendable = attendable
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          access_id == o.access_id &&
          first_name == o.first_name &&
          last_name == o.last_name &&
          full_name == o.full_name &&
          preferred_name == o.preferred_name &&
          birth_name == o.birth_name &&
          gender == o.gender &&
          identifier == o.identifier &&
          identifier_type == o.identifier_type &&
          email == o.email &&
          login_email == o.login_email &&
          birthday_on == o.birthday_on &&
          nationality == o.nationality &&
          address_line_1 == o.address_line_1 &&
          address_line_2 == o.address_line_2 &&
          postal_code == o.postal_code &&
          city == o.city &&
          state == o.state &&
          country == o.country &&
          bank_number == o.bank_number &&
          swift_bic == o.swift_bic &&
          bank_number_format == o.bank_number_format &&
          company_id == o.company_id &&
          legal_entity_id == o.legal_entity_id &&
          location_id == o.location_id &&
          default_work_area_id == o.default_work_area_id &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          social_security_number == o.social_security_number &&
          is_terminating == o.is_terminating &&
          terminated_on == o.terminated_on &&
          termination_reason_type == o.termination_reason_type &&
          termination_reason == o.termination_reason &&
          termination_observations == o.termination_observations &&
          manager_id == o.manager_id &&
          timeoff_manager_id == o.timeoff_manager_id &&
          phone_number == o.phone_number &&
          company_identifier == o.company_identifier &&
          age_number == o.age_number &&
          termination_type_description == o.termination_type_description &&
          contact_name == o.contact_name &&
          contact_number == o.contact_number &&
          personal_email == o.personal_email &&
          seniority_calculation_date == o.seniority_calculation_date &&
          communications_email == o.communications_email &&
          unconfirmed_communications_email == o.unconfirmed_communications_email &&
          pronouns == o.pronouns &&
          active == o.active &&
          disability_percentage_cents == o.disability_percentage_cents &&
          identifier_expiration_date == o.identifier_expiration_date &&
          attendable == o.attendable &&
          country_of_birth == o.country_of_birth &&
          birthplace == o.birthplace
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, access_id, first_name, last_name, full_name, preferred_name, birth_name, gender, identifier, identifier_type, email, login_email, birthday_on, nationality, address_line_1, address_line_2, postal_code, city, state, country, bank_number, swift_bic, bank_number_format, company_id, legal_entity_id, location_id, default_work_area_id, created_at, updated_at, social_security_number, is_terminating, terminated_on, termination_reason_type, termination_reason, termination_observations, manager_id, timeoff_manager_id, phone_number, company_identifier, age_number, termination_type_description, contact_name, contact_number, personal_email, seniority_calculation_date, communications_email, unconfirmed_communications_email, pronouns, active, disability_percentage_cents, identifier_expiration_date, attendable, country_of_birth, birthplace].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
