=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F
  class FinanceLedgerAccountResourcesUpsertPostRequest < ApiModelBase
    # Factorial unique identifier.
    attr_accessor :id

    # Name of the ledger account resource.
    attr_accessor :name

    # Number of the ledger account resource.
    attr_accessor :number

    # External identifier.
    attr_accessor :external_id

    # Legal entity identifier.
    attr_accessor :legal_entity_id

    # Finance account identifier.
    attr_accessor :account_id

    # Factorial unique identifier of the resource associated to the ledger account resource.
    attr_accessor :resource_id

    # Ledger account resource type.
    attr_accessor :resource_type

    # Ledger account balance type.
    attr_accessor :balance_type

    # Ledger account operation type.
    attr_accessor :operation_type

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'number' => :'number',
        :'external_id' => :'external_id',
        :'legal_entity_id' => :'legal_entity_id',
        :'account_id' => :'account_id',
        :'resource_id' => :'resource_id',
        :'resource_type' => :'resource_type',
        :'balance_type' => :'balance_type',
        :'operation_type' => :'operation_type'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'number' => :'String',
        :'external_id' => :'String',
        :'legal_entity_id' => :'String',
        :'account_id' => :'String',
        :'resource_id' => :'String',
        :'resource_type' => :'String',
        :'balance_type' => :'String',
        :'operation_type' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::FinanceLedgerAccountResourcesUpsertPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::FinanceLedgerAccountResourcesUpsertPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'legal_entity_id')
        self.legal_entity_id = attributes[:'legal_entity_id']
      else
        self.legal_entity_id = nil
      end

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      end

      if attributes.key?(:'resource_id')
        self.resource_id = attributes[:'resource_id']
      end

      if attributes.key?(:'resource_type')
        self.resource_type = attributes[:'resource_type']
      else
        self.resource_type = nil
      end

      if attributes.key?(:'balance_type')
        self.balance_type = attributes[:'balance_type']
      end

      if attributes.key?(:'operation_type')
        self.operation_type = attributes[:'operation_type']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @legal_entity_id.nil?
        invalid_properties.push('invalid value for "legal_entity_id", legal_entity_id cannot be nil.')
      end

      if @resource_type.nil?
        invalid_properties.push('invalid value for "resource_type", resource_type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @legal_entity_id.nil?
      return false if @resource_type.nil?
      resource_type_validator = EnumAttributeValidator.new('String', ["customcategory", "bankaccount", "vendor", "taxtype", "invoice", "payrollconcept"])
      return false unless resource_type_validator.valid?(@resource_type)
      balance_type_validator = EnumAttributeValidator.new('String', ["credit", "debit"])
      return false unless balance_type_validator.valid?(@balance_type)
      operation_type_validator = EnumAttributeValidator.new('String', ["purchase", "sale"])
      return false unless operation_type_validator.valid?(@operation_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] legal_entity_id Value to be assigned
    def legal_entity_id=(legal_entity_id)
      if legal_entity_id.nil?
        @legal_entity_id = nil
        return
      end

      @legal_entity_id = legal_entity_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] resource_type Object to be assigned
    def resource_type=(resource_type)
      validator = EnumAttributeValidator.new('String', ["customcategory", "bankaccount", "vendor", "taxtype", "invoice", "payrollconcept"])
      unless validator.valid?(resource_type)
        fail ArgumentError, "invalid value for \"resource_type\", must be one of #{validator.allowable_values}."
      end
      @resource_type = resource_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] balance_type Object to be assigned
    def balance_type=(balance_type)
      validator = EnumAttributeValidator.new('String', ["credit", "debit"])
      unless validator.valid?(balance_type)
        fail ArgumentError, "invalid value for \"balance_type\", must be one of #{validator.allowable_values}."
      end
      @balance_type = balance_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] operation_type Object to be assigned
    def operation_type=(operation_type)
      validator = EnumAttributeValidator.new('String', ["purchase", "sale"])
      unless validator.valid?(operation_type)
        fail ArgumentError, "invalid value for \"operation_type\", must be one of #{validator.allowable_values}."
      end
      @operation_type = operation_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          number == o.number &&
          external_id == o.external_id &&
          legal_entity_id == o.legal_entity_id &&
          account_id == o.account_id &&
          resource_id == o.resource_id &&
          resource_type == o.resource_type &&
          balance_type == o.balance_type &&
          operation_type == o.operation_type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, number, external_id, legal_entity_id, account_id, resource_id, resource_type, balance_type, operation_type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
