=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-10-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F::Api
  class FinanceFinancialDocumentsIdPutRequest < ApiModelBase
    # Company identifier, as returned by the credentials endpoint (`/resources/api_public/credentials`).
    attr_accessor :company_id

    # Identifier of the financial document to update.
    attr_accessor :id

    # Document currency (ISO 4217).
    attr_accessor :currency

    # Total amount in cents. Ignored when line_items are provided, since the line items own the totals.
    attr_accessor :total_amount_cents

    # Document number. Must be unique per vendor for purchases; a duplicate returns a 409 with the same machine-readable invoice_number error key as the create endpoint.
    attr_accessor :document_number

    # Document date.
    attr_accessor :document_date

    # Due date.
    attr_accessor :due_date

    # Status of the document. Transitions have real side effects: `sent_to_pay` enqueues a payment request in Factorial, and `paid` marks the document as paid (manual payment). Once a document is `sent_to_pay`, its payment lifecycle is owned by the payment flow in Factorial — do not set `paid` manually on it; the payment reconciliation does.
    attr_accessor :status

    # Validation timestamp, as returned by the read endpoint (e.g. `2020-01-01T00:00:00.000Z`). Setting it on a not-yet-validated document validates it: the strict required-field set (currency, amounts, document number, dates, vendor, legal entity) is enforced on that transition, not before.
    attr_accessor :validated_at

    # Tax breakdown, as returned by the read endpoint — send back what you read (adjusted to your changes). Replaced as sent; ignored when line_items are provided, since the line items own the totals.
    attr_accessor :taxes

    # Purchase-invoice line items. Rows are addressed by id, never by position: rows carrying an id update the matching line item, rows without an id create new ones, and persisted rows missing from the set are deleted. Send an empty array to remove all line items, or omit the field entirely to leave them untouched. When present they own the document totals.
    attr_accessor :line_items

    # Legal entity identifier of the financial document.
    attr_accessor :legal_entity_id

    # Vendor identifier (Finance contact).
    attr_accessor :vendor_id

    # Type of the financial document. One of `invoice`, `credit_note`, `receipt`.
    attr_accessor :document_type

    # For credit notes, the referenced original document by internal id (e.g. `135`).
    attr_accessor :parent_financial_document_id

    # Free-text internal notes about the financial document. Kept unchanged when the field is absent.
    attr_accessor :additional_information

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'company_id' => :'company_id',
        :'id' => :'id',
        :'currency' => :'currency',
        :'total_amount_cents' => :'total_amount_cents',
        :'document_number' => :'document_number',
        :'document_date' => :'document_date',
        :'due_date' => :'due_date',
        :'status' => :'status',
        :'validated_at' => :'validated_at',
        :'taxes' => :'taxes',
        :'line_items' => :'line_items',
        :'legal_entity_id' => :'legal_entity_id',
        :'vendor_id' => :'vendor_id',
        :'document_type' => :'document_type',
        :'parent_financial_document_id' => :'parent_financial_document_id',
        :'additional_information' => :'additional_information'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'company_id' => :'String',
        :'id' => :'String',
        :'currency' => :'String',
        :'total_amount_cents' => :'Integer',
        :'document_number' => :'String',
        :'document_date' => :'String',
        :'due_date' => :'String',
        :'status' => :'String',
        :'validated_at' => :'String',
        :'taxes' => :'Array<FinanceFinancialDocumentsIdPutRequestTaxesInner>',
        :'line_items' => :'Array<FinanceFinancialDocumentsPostRequestLineItemsInner>',
        :'legal_entity_id' => :'String',
        :'vendor_id' => :'String',
        :'document_type' => :'String',
        :'parent_financial_document_id' => :'String',
        :'additional_information' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::Api::FinanceFinancialDocumentsIdPutRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::Api::FinanceFinancialDocumentsIdPutRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      else
        self.company_id = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'total_amount_cents')
        self.total_amount_cents = attributes[:'total_amount_cents']
      end

      if attributes.key?(:'document_number')
        self.document_number = attributes[:'document_number']
      end

      if attributes.key?(:'document_date')
        self.document_date = attributes[:'document_date']
      end

      if attributes.key?(:'due_date')
        self.due_date = attributes[:'due_date']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'validated_at')
        self.validated_at = attributes[:'validated_at']
      end

      if attributes.key?(:'taxes')
        if (value = attributes[:'taxes']).is_a?(Array)
          self.taxes = value
        end
      else
        self.taxes = nil
      end

      if attributes.key?(:'line_items')
        if (value = attributes[:'line_items']).is_a?(Array)
          self.line_items = value
        end
      end

      if attributes.key?(:'legal_entity_id')
        self.legal_entity_id = attributes[:'legal_entity_id']
      end

      if attributes.key?(:'vendor_id')
        self.vendor_id = attributes[:'vendor_id']
      end

      if attributes.key?(:'document_type')
        self.document_type = attributes[:'document_type']
      end

      if attributes.key?(:'parent_financial_document_id')
        self.parent_financial_document_id = attributes[:'parent_financial_document_id']
      end

      if attributes.key?(:'additional_information')
        self.additional_information = attributes[:'additional_information']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @company_id.nil?
        invalid_properties.push('invalid value for "company_id", company_id cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @taxes.nil?
        invalid_properties.push('invalid value for "taxes", taxes cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @company_id.nil?
      return false if @id.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["processing", "review", "sent_to_pay", "paid"])
      return false unless status_validator.valid?(@status)
      return false if @taxes.nil?
      document_type_validator = EnumAttributeValidator.new('String', ["invoice", "credit_note", "receipt"])
      return false unless document_type_validator.valid?(@document_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] company_id Value to be assigned
    def company_id=(company_id)
      if company_id.nil?
        @company_id = nil
        return
      end

      @company_id = company_id
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        @id = nil
        return
      end

      @id = id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["processing", "review", "sent_to_pay", "paid"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] taxes Value to be assigned
    def taxes=(taxes)
      if taxes.nil?
        @taxes = nil
        return
      end

      @taxes = taxes
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] document_type Object to be assigned
    def document_type=(document_type)
      validator = EnumAttributeValidator.new('String', ["invoice", "credit_note", "receipt"])
      unless validator.valid?(document_type)
        fail ArgumentError, "invalid value for \"document_type\", must be one of #{validator.allowable_values}."
      end
      @document_type = document_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          company_id == o.company_id &&
          id == o.id &&
          currency == o.currency &&
          total_amount_cents == o.total_amount_cents &&
          document_number == o.document_number &&
          document_date == o.document_date &&
          due_date == o.due_date &&
          status == o.status &&
          validated_at == o.validated_at &&
          taxes == o.taxes &&
          line_items == o.line_items &&
          legal_entity_id == o.legal_entity_id &&
          vendor_id == o.vendor_id &&
          document_type == o.document_type &&
          parent_financial_document_id == o.parent_financial_document_id &&
          additional_information == o.additional_information
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [company_id, id, currency, total_amount_cents, document_number, document_date, due_date, status, validated_at, taxes, line_items, legal_entity_id, vendor_id, document_type, parent_financial_document_id, additional_information].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
