=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-10-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F::Api
  # data of the item to be synced
  class IntegrationsSyncableItemSyncPayload < ApiModelBase
    attr_accessor :id

    attr_accessor :employee_id

    attr_accessor :payroll_concept_id

    attr_accessor :legal_entity_id

    attr_accessor :company_id

    attr_accessor :category_id

    attr_accessor :subcategory_id

    attr_accessor :ledger_account_id

    attr_accessor :leave_type_id

    attr_accessor :leave_type_name

    attr_accessor :translated_leave_type_name

    attr_accessor :employee_full_name

    attr_accessor :legal_entity_name

    attr_accessor :start_time

    attr_accessor :days_taken

    attr_accessor :created_at

    attr_accessor :contract_working_hours

    attr_accessor :contract_working_hours_frequency

    attr_accessor :contract_working_week_days

    attr_accessor :contract_fr_forfait_jours

    attr_accessor :project_id

    attr_accessor :subproject_ids

    attr_accessor :cost_center_ids

    attr_accessor :files

    attr_accessor :taxes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'employee_id' => :'employee_id',
        :'payroll_concept_id' => :'payroll_concept_id',
        :'legal_entity_id' => :'legal_entity_id',
        :'company_id' => :'company_id',
        :'category_id' => :'category_id',
        :'subcategory_id' => :'subcategory_id',
        :'ledger_account_id' => :'ledger_account_id',
        :'leave_type_id' => :'leave_type_id',
        :'leave_type_name' => :'leave_type_name',
        :'translated_leave_type_name' => :'translated_leave_type_name',
        :'employee_full_name' => :'employee_full_name',
        :'legal_entity_name' => :'legal_entity_name',
        :'start_time' => :'start_time',
        :'days_taken' => :'days_taken',
        :'created_at' => :'created_at',
        :'contract_working_hours' => :'contract_working_hours',
        :'contract_working_hours_frequency' => :'contract_working_hours_frequency',
        :'contract_working_week_days' => :'contract_working_week_days',
        :'contract_fr_forfait_jours' => :'contract_fr_forfait_jours',
        :'project_id' => :'project_id',
        :'subproject_ids' => :'subproject_ids',
        :'cost_center_ids' => :'cost_center_ids',
        :'files' => :'files',
        :'taxes' => :'taxes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'employee_id' => :'String',
        :'payroll_concept_id' => :'String',
        :'legal_entity_id' => :'String',
        :'company_id' => :'String',
        :'category_id' => :'String',
        :'subcategory_id' => :'String',
        :'ledger_account_id' => :'String',
        :'leave_type_id' => :'String',
        :'leave_type_name' => :'String',
        :'translated_leave_type_name' => :'String',
        :'employee_full_name' => :'String',
        :'legal_entity_name' => :'String',
        :'start_time' => :'String',
        :'days_taken' => :'Float',
        :'created_at' => :'String',
        :'contract_working_hours' => :'Integer',
        :'contract_working_hours_frequency' => :'String',
        :'contract_working_week_days' => :'String',
        :'contract_fr_forfait_jours' => :'Boolean',
        :'project_id' => :'String',
        :'subproject_ids' => :'Array<String>',
        :'cost_center_ids' => :'Array<IntegrationsSyncableItemSyncPayloadCostCenterIdsInner>',
        :'files' => :'Array<IntegrationsSyncableItemSyncPayloadCostCenterIdsInner>',
        :'taxes' => :'Array<IntegrationsSyncableItemSyncPayloadTaxesInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::Api::IntegrationsSyncableItemSyncPayload` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::Api::IntegrationsSyncableItemSyncPayload`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'employee_id')
        self.employee_id = attributes[:'employee_id']
      end

      if attributes.key?(:'payroll_concept_id')
        self.payroll_concept_id = attributes[:'payroll_concept_id']
      end

      if attributes.key?(:'legal_entity_id')
        self.legal_entity_id = attributes[:'legal_entity_id']
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      end

      if attributes.key?(:'category_id')
        self.category_id = attributes[:'category_id']
      end

      if attributes.key?(:'subcategory_id')
        self.subcategory_id = attributes[:'subcategory_id']
      end

      if attributes.key?(:'ledger_account_id')
        self.ledger_account_id = attributes[:'ledger_account_id']
      end

      if attributes.key?(:'leave_type_id')
        self.leave_type_id = attributes[:'leave_type_id']
      end

      if attributes.key?(:'leave_type_name')
        self.leave_type_name = attributes[:'leave_type_name']
      end

      if attributes.key?(:'translated_leave_type_name')
        self.translated_leave_type_name = attributes[:'translated_leave_type_name']
      end

      if attributes.key?(:'employee_full_name')
        self.employee_full_name = attributes[:'employee_full_name']
      end

      if attributes.key?(:'legal_entity_name')
        self.legal_entity_name = attributes[:'legal_entity_name']
      end

      if attributes.key?(:'start_time')
        self.start_time = attributes[:'start_time']
      end

      if attributes.key?(:'days_taken')
        self.days_taken = attributes[:'days_taken']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'contract_working_hours')
        self.contract_working_hours = attributes[:'contract_working_hours']
      end

      if attributes.key?(:'contract_working_hours_frequency')
        self.contract_working_hours_frequency = attributes[:'contract_working_hours_frequency']
      end

      if attributes.key?(:'contract_working_week_days')
        self.contract_working_week_days = attributes[:'contract_working_week_days']
      end

      if attributes.key?(:'contract_fr_forfait_jours')
        self.contract_fr_forfait_jours = attributes[:'contract_fr_forfait_jours']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'subproject_ids')
        if (value = attributes[:'subproject_ids']).is_a?(Array)
          self.subproject_ids = value
        end
      end

      if attributes.key?(:'cost_center_ids')
        if (value = attributes[:'cost_center_ids']).is_a?(Array)
          self.cost_center_ids = value
        end
      end

      if attributes.key?(:'files')
        if (value = attributes[:'files']).is_a?(Array)
          self.files = value
        end
      end

      if attributes.key?(:'taxes')
        if (value = attributes[:'taxes']).is_a?(Array)
          self.taxes = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          employee_id == o.employee_id &&
          payroll_concept_id == o.payroll_concept_id &&
          legal_entity_id == o.legal_entity_id &&
          company_id == o.company_id &&
          category_id == o.category_id &&
          subcategory_id == o.subcategory_id &&
          ledger_account_id == o.ledger_account_id &&
          leave_type_id == o.leave_type_id &&
          leave_type_name == o.leave_type_name &&
          translated_leave_type_name == o.translated_leave_type_name &&
          employee_full_name == o.employee_full_name &&
          legal_entity_name == o.legal_entity_name &&
          start_time == o.start_time &&
          days_taken == o.days_taken &&
          created_at == o.created_at &&
          contract_working_hours == o.contract_working_hours &&
          contract_working_hours_frequency == o.contract_working_hours_frequency &&
          contract_working_week_days == o.contract_working_week_days &&
          contract_fr_forfait_jours == o.contract_fr_forfait_jours &&
          project_id == o.project_id &&
          subproject_ids == o.subproject_ids &&
          cost_center_ids == o.cost_center_ids &&
          files == o.files &&
          taxes == o.taxes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, employee_id, payroll_concept_id, legal_entity_id, company_id, category_id, subcategory_id, ledger_account_id, leave_type_id, leave_type_name, translated_leave_type_name, employee_full_name, legal_entity_name, start_time, days_taken, created_at, contract_working_hours, contract_working_hours_frequency, contract_working_week_days, contract_fr_forfait_jours, project_id, subproject_ids, cost_center_ids, files, taxes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
