=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F
  class PayrollIntegrationsBaseCode < ApiModelBase
    # Code identifier
    attr_accessor :id

    # Company ID where the code belongs to
    attr_accessor :company_id

    # Code value
    attr_accessor :code

    # Related object ID. Used together with codeable_type
    attr_accessor :codeable_id

    # Related object type. Used together with codeable_id
    attr_accessor :codeable_type

    # Integration name
    attr_accessor :integration

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'company_id' => :'company_id',
        :'code' => :'code',
        :'codeable_id' => :'codeable_id',
        :'codeable_type' => :'codeable_type',
        :'integration' => :'integration'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'company_id' => :'String',
        :'code' => :'String',
        :'codeable_id' => :'String',
        :'codeable_type' => :'String',
        :'integration' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::PayrollIntegrationsBaseCode` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::PayrollIntegrationsBaseCode`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      else
        self.company_id = nil
      end

      if attributes.key?(:'code')
        self.code = attributes[:'code']
      else
        self.code = nil
      end

      if attributes.key?(:'codeable_id')
        self.codeable_id = attributes[:'codeable_id']
      else
        self.codeable_id = nil
      end

      if attributes.key?(:'codeable_type')
        self.codeable_type = attributes[:'codeable_type']
      else
        self.codeable_type = nil
      end

      if attributes.key?(:'integration')
        self.integration = attributes[:'integration']
      else
        self.integration = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @company_id.nil?
        invalid_properties.push('invalid value for "company_id", company_id cannot be nil.')
      end

      if @code.nil?
        invalid_properties.push('invalid value for "code", code cannot be nil.')
      end

      if @codeable_id.nil?
        invalid_properties.push('invalid value for "codeable_id", codeable_id cannot be nil.')
      end

      if @codeable_type.nil?
        invalid_properties.push('invalid value for "codeable_type", codeable_type cannot be nil.')
      end

      if @integration.nil?
        invalid_properties.push('invalid value for "integration", integration cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @company_id.nil?
      return false if @code.nil?
      return false if @codeable_id.nil?
      return false if @codeable_type.nil?
      return false if @integration.nil?
      integration_validator = EnumAttributeValidator.new('String', ["a3innuva", "a3nom", "agenda", "paierh", "yeap_paierh", "silae", "sage100", "datev", "datev_api", "datev_lug_api", "datev_lauds", "team_system", "zucchetti", "gispaghe", "job_sistemi"])
      return false unless integration_validator.valid?(@integration)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        @id = nil
        return
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] company_id Value to be assigned
    def company_id=(company_id)
      if company_id.nil?
        @company_id = nil
        return
      end

      @company_id = company_id
    end

    # Custom attribute writer method with validation
    # @param [Object] code Value to be assigned
    def code=(code)
      if code.nil?
        @code = nil
        return
      end

      @code = code
    end

    # Custom attribute writer method with validation
    # @param [Object] codeable_id Value to be assigned
    def codeable_id=(codeable_id)
      if codeable_id.nil?
        @codeable_id = nil
        return
      end

      @codeable_id = codeable_id
    end

    # Custom attribute writer method with validation
    # @param [Object] codeable_type Value to be assigned
    def codeable_type=(codeable_type)
      if codeable_type.nil?
        @codeable_type = nil
        return
      end

      @codeable_type = codeable_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] integration Object to be assigned
    def integration=(integration)
      validator = EnumAttributeValidator.new('String', ["a3innuva", "a3nom", "agenda", "paierh", "yeap_paierh", "silae", "sage100", "datev", "datev_api", "datev_lug_api", "datev_lauds", "team_system", "zucchetti", "gispaghe", "job_sistemi"])
      unless validator.valid?(integration)
        fail ArgumentError, "invalid value for \"integration\", must be one of #{validator.allowable_values}."
      end
      @integration = integration
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          company_id == o.company_id &&
          code == o.code &&
          codeable_id == o.codeable_id &&
          codeable_type == o.codeable_type &&
          integration == o.integration
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, company_id, code, codeable_id, codeable_type, integration].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
