=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F
  class ProjectManagementPlannedRecordsBulkCreatePostRequest < ApiModelBase
    # The project worker ids to create the planned records for
    attr_accessor :project_worker_ids

    # The start date to create the planned records for
    attr_accessor :start_date

    # The end date to create the planned records for
    attr_accessor :end_date

    # The daily minutes to create the planned records for
    attr_accessor :daily_minutes

    # The subproject id to create the planned records for
    attr_accessor :subproject_id

    # The week days to create the planned records for, start in Sunday 0 and end in Saturday 6
    attr_accessor :week_days

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'project_worker_ids' => :'project_worker_ids',
        :'start_date' => :'start_date',
        :'end_date' => :'end_date',
        :'daily_minutes' => :'daily_minutes',
        :'subproject_id' => :'subproject_id',
        :'week_days' => :'week_days'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'project_worker_ids' => :'Array<String>',
        :'start_date' => :'String',
        :'end_date' => :'String',
        :'daily_minutes' => :'Integer',
        :'subproject_id' => :'String',
        :'week_days' => :'Array<Integer>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::ProjectManagementPlannedRecordsBulkCreatePostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::ProjectManagementPlannedRecordsBulkCreatePostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'project_worker_ids')
        if (value = attributes[:'project_worker_ids']).is_a?(Array)
          self.project_worker_ids = value
        end
      else
        self.project_worker_ids = nil
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      else
        self.start_date = nil
      end

      if attributes.key?(:'end_date')
        self.end_date = attributes[:'end_date']
      else
        self.end_date = nil
      end

      if attributes.key?(:'daily_minutes')
        self.daily_minutes = attributes[:'daily_minutes']
      else
        self.daily_minutes = nil
      end

      if attributes.key?(:'subproject_id')
        self.subproject_id = attributes[:'subproject_id']
      end

      if attributes.key?(:'week_days')
        if (value = attributes[:'week_days']).is_a?(Array)
          self.week_days = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @project_worker_ids.nil?
        invalid_properties.push('invalid value for "project_worker_ids", project_worker_ids cannot be nil.')
      end

      if @start_date.nil?
        invalid_properties.push('invalid value for "start_date", start_date cannot be nil.')
      end

      if @end_date.nil?
        invalid_properties.push('invalid value for "end_date", end_date cannot be nil.')
      end

      if @daily_minutes.nil?
        invalid_properties.push('invalid value for "daily_minutes", daily_minutes cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @project_worker_ids.nil?
      return false if @start_date.nil?
      return false if @end_date.nil?
      return false if @daily_minutes.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] project_worker_ids Value to be assigned
    def project_worker_ids=(project_worker_ids)
      if project_worker_ids.nil?
        @project_worker_ids = nil
        return
      end

      @project_worker_ids = project_worker_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] start_date Value to be assigned
    def start_date=(start_date)
      if start_date.nil?
        @start_date = nil
        return
      end

      @start_date = start_date
    end

    # Custom attribute writer method with validation
    # @param [Object] end_date Value to be assigned
    def end_date=(end_date)
      if end_date.nil?
        @end_date = nil
        return
      end

      @end_date = end_date
    end

    # Custom attribute writer method with validation
    # @param [Object] daily_minutes Value to be assigned
    def daily_minutes=(daily_minutes)
      if daily_minutes.nil?
        @daily_minutes = nil
        return
      end

      @daily_minutes = daily_minutes
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          project_worker_ids == o.project_worker_ids &&
          start_date == o.start_date &&
          end_date == o.end_date &&
          daily_minutes == o.daily_minutes &&
          subproject_id == o.subproject_id &&
          week_days == o.week_days
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [project_worker_ids, start_date, end_date, daily_minutes, subproject_id, week_days].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
