=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F
  class TimeoffAllowanceStatsNew < ApiModelBase
    # A virtual ID for the allowance stat, composed of employee_id/allowance_id/reference_date. Cannot be used to fetch this resource.
    attr_accessor :id

    # ID of the allowance these stats belong to.
    attr_accessor :allowance_id

    # ID of the employee these stats belong to.
    attr_accessor :employee_id

    # Calendar year used to scope cycle calculations.
    attr_accessor :year

    # Array of cycle objects describing each accrual period for the allowance.
    attr_accessor :cycles

    # Carry over entries between cycles, typed as an array of CycleCarryOver value objects.
    attr_accessor :cycle_carry_overs

    # Total carried over units accumulated from previous cycles.
    attr_accessor :accumulated_carry_over

    # Remaining usable allowance units at the reference date, after usage, carry-over, and incidence adjustments.
    attr_accessor :available_days

    # Total accrued/generated allowance units up to the reference date.
    attr_accessor :total_accrued_units

    # Total entitlement for the cycle used by the Total row in counters (accrued + carry over + incidences, with backend cap/rounding rules applied before incidences).
    attr_accessor :total

    # Sum of incidence units (adjustments) applied to this allowance.
    attr_accessor :incidences

    # Sum of incidence units scoped to 'accrued' target balance for the current cycle, filtered by cycle coverage rules.
    attr_accessor :accrued_incidences

    # Sum of incidence units scoped to non-accrued target balances for the current cycle, filtered by cycle coverage rules.
    attr_accessor :available_incidences

    # Maximum balance cap enforced by policy (null if unlimited or no cap).
    attr_accessor :max_balance_cap

    # Base policy entitlement for the cycle in allowance units (days or hours depending on allowance setup), before proration and adjustments.
    attr_accessor :policy_allowance

    # Allowance days after proration based on employee tenure or configuration.
    attr_accessor :prorated_allowance_days

    # Total allowance units in decimal form (null if not computed for the reference date yet).
    attr_accessor :total_in_decimal

    # Units from carry over already consumed.
    attr_accessor :used_carry_over

    # Total used days (converted from units) up to the reference date.
    attr_accessor :used_days

    # Units consumed strictly until the given reference date (excludes future approved leaves).
    attr_accessor :used_units_until_reference_date

    # Pending units scheduled (approved in the future) not yet counted as used until the reference date.
    attr_accessor :outstanding_units

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'allowance_id' => :'allowance_id',
        :'employee_id' => :'employee_id',
        :'year' => :'year',
        :'cycles' => :'cycles',
        :'cycle_carry_overs' => :'cycle_carry_overs',
        :'accumulated_carry_over' => :'accumulated_carry_over',
        :'available_days' => :'available_days',
        :'total_accrued_units' => :'total_accrued_units',
        :'total' => :'total',
        :'incidences' => :'incidences',
        :'accrued_incidences' => :'accrued_incidences',
        :'available_incidences' => :'available_incidences',
        :'max_balance_cap' => :'max_balance_cap',
        :'policy_allowance' => :'policy_allowance',
        :'prorated_allowance_days' => :'prorated_allowance_days',
        :'total_in_decimal' => :'total_in_decimal',
        :'used_carry_over' => :'used_carry_over',
        :'used_days' => :'used_days',
        :'used_units_until_reference_date' => :'used_units_until_reference_date',
        :'outstanding_units' => :'outstanding_units'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'allowance_id' => :'String',
        :'employee_id' => :'String',
        :'year' => :'Integer',
        :'cycles' => :'Array<Object>',
        :'cycle_carry_overs' => :'Array<Object>',
        :'accumulated_carry_over' => :'String',
        :'available_days' => :'String',
        :'total_accrued_units' => :'String',
        :'total' => :'String',
        :'incidences' => :'String',
        :'accrued_incidences' => :'String',
        :'available_incidences' => :'String',
        :'max_balance_cap' => :'String',
        :'policy_allowance' => :'String',
        :'prorated_allowance_days' => :'String',
        :'total_in_decimal' => :'String',
        :'used_carry_over' => :'String',
        :'used_days' => :'String',
        :'used_units_until_reference_date' => :'String',
        :'outstanding_units' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::TimeoffAllowanceStatsNew` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::TimeoffAllowanceStatsNew`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'allowance_id')
        self.allowance_id = attributes[:'allowance_id']
      else
        self.allowance_id = nil
      end

      if attributes.key?(:'employee_id')
        self.employee_id = attributes[:'employee_id']
      else
        self.employee_id = nil
      end

      if attributes.key?(:'year')
        self.year = attributes[:'year']
      else
        self.year = nil
      end

      if attributes.key?(:'cycles')
        if (value = attributes[:'cycles']).is_a?(Array)
          self.cycles = value
        end
      else
        self.cycles = nil
      end

      if attributes.key?(:'cycle_carry_overs')
        if (value = attributes[:'cycle_carry_overs']).is_a?(Array)
          self.cycle_carry_overs = value
        end
      else
        self.cycle_carry_overs = nil
      end

      if attributes.key?(:'accumulated_carry_over')
        self.accumulated_carry_over = attributes[:'accumulated_carry_over']
      else
        self.accumulated_carry_over = nil
      end

      if attributes.key?(:'available_days')
        self.available_days = attributes[:'available_days']
      else
        self.available_days = nil
      end

      if attributes.key?(:'total_accrued_units')
        self.total_accrued_units = attributes[:'total_accrued_units']
      else
        self.total_accrued_units = nil
      end

      if attributes.key?(:'total')
        self.total = attributes[:'total']
      else
        self.total = nil
      end

      if attributes.key?(:'incidences')
        self.incidences = attributes[:'incidences']
      else
        self.incidences = nil
      end

      if attributes.key?(:'accrued_incidences')
        self.accrued_incidences = attributes[:'accrued_incidences']
      else
        self.accrued_incidences = nil
      end

      if attributes.key?(:'available_incidences')
        self.available_incidences = attributes[:'available_incidences']
      else
        self.available_incidences = nil
      end

      if attributes.key?(:'max_balance_cap')
        self.max_balance_cap = attributes[:'max_balance_cap']
      end

      if attributes.key?(:'policy_allowance')
        self.policy_allowance = attributes[:'policy_allowance']
      else
        self.policy_allowance = nil
      end

      if attributes.key?(:'prorated_allowance_days')
        self.prorated_allowance_days = attributes[:'prorated_allowance_days']
      else
        self.prorated_allowance_days = nil
      end

      if attributes.key?(:'total_in_decimal')
        self.total_in_decimal = attributes[:'total_in_decimal']
      end

      if attributes.key?(:'used_carry_over')
        self.used_carry_over = attributes[:'used_carry_over']
      else
        self.used_carry_over = nil
      end

      if attributes.key?(:'used_days')
        self.used_days = attributes[:'used_days']
      else
        self.used_days = nil
      end

      if attributes.key?(:'used_units_until_reference_date')
        self.used_units_until_reference_date = attributes[:'used_units_until_reference_date']
      else
        self.used_units_until_reference_date = nil
      end

      if attributes.key?(:'outstanding_units')
        self.outstanding_units = attributes[:'outstanding_units']
      else
        self.outstanding_units = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @allowance_id.nil?
        invalid_properties.push('invalid value for "allowance_id", allowance_id cannot be nil.')
      end

      if @employee_id.nil?
        invalid_properties.push('invalid value for "employee_id", employee_id cannot be nil.')
      end

      if @year.nil?
        invalid_properties.push('invalid value for "year", year cannot be nil.')
      end

      if @cycles.nil?
        invalid_properties.push('invalid value for "cycles", cycles cannot be nil.')
      end

      if @cycle_carry_overs.nil?
        invalid_properties.push('invalid value for "cycle_carry_overs", cycle_carry_overs cannot be nil.')
      end

      if @accumulated_carry_over.nil?
        invalid_properties.push('invalid value for "accumulated_carry_over", accumulated_carry_over cannot be nil.')
      end

      if @available_days.nil?
        invalid_properties.push('invalid value for "available_days", available_days cannot be nil.')
      end

      if @total_accrued_units.nil?
        invalid_properties.push('invalid value for "total_accrued_units", total_accrued_units cannot be nil.')
      end

      if @total.nil?
        invalid_properties.push('invalid value for "total", total cannot be nil.')
      end

      if @incidences.nil?
        invalid_properties.push('invalid value for "incidences", incidences cannot be nil.')
      end

      if @accrued_incidences.nil?
        invalid_properties.push('invalid value for "accrued_incidences", accrued_incidences cannot be nil.')
      end

      if @available_incidences.nil?
        invalid_properties.push('invalid value for "available_incidences", available_incidences cannot be nil.')
      end

      if @policy_allowance.nil?
        invalid_properties.push('invalid value for "policy_allowance", policy_allowance cannot be nil.')
      end

      if @prorated_allowance_days.nil?
        invalid_properties.push('invalid value for "prorated_allowance_days", prorated_allowance_days cannot be nil.')
      end

      if @used_carry_over.nil?
        invalid_properties.push('invalid value for "used_carry_over", used_carry_over cannot be nil.')
      end

      if @used_days.nil?
        invalid_properties.push('invalid value for "used_days", used_days cannot be nil.')
      end

      if @used_units_until_reference_date.nil?
        invalid_properties.push('invalid value for "used_units_until_reference_date", used_units_until_reference_date cannot be nil.')
      end

      if @outstanding_units.nil?
        invalid_properties.push('invalid value for "outstanding_units", outstanding_units cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @allowance_id.nil?
      return false if @employee_id.nil?
      return false if @year.nil?
      return false if @cycles.nil?
      return false if @cycle_carry_overs.nil?
      return false if @accumulated_carry_over.nil?
      return false if @available_days.nil?
      return false if @total_accrued_units.nil?
      return false if @total.nil?
      return false if @incidences.nil?
      return false if @accrued_incidences.nil?
      return false if @available_incidences.nil?
      return false if @policy_allowance.nil?
      return false if @prorated_allowance_days.nil?
      return false if @used_carry_over.nil?
      return false if @used_days.nil?
      return false if @used_units_until_reference_date.nil?
      return false if @outstanding_units.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        @id = nil
        return
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] allowance_id Value to be assigned
    def allowance_id=(allowance_id)
      if allowance_id.nil?
        @allowance_id = nil
        return
      end

      @allowance_id = allowance_id
    end

    # Custom attribute writer method with validation
    # @param [Object] employee_id Value to be assigned
    def employee_id=(employee_id)
      if employee_id.nil?
        @employee_id = nil
        return
      end

      @employee_id = employee_id
    end

    # Custom attribute writer method with validation
    # @param [Object] year Value to be assigned
    def year=(year)
      if year.nil?
        @year = nil
        return
      end

      @year = year
    end

    # Custom attribute writer method with validation
    # @param [Object] cycles Value to be assigned
    def cycles=(cycles)
      if cycles.nil?
        @cycles = nil
        return
      end

      @cycles = cycles
    end

    # Custom attribute writer method with validation
    # @param [Object] cycle_carry_overs Value to be assigned
    def cycle_carry_overs=(cycle_carry_overs)
      if cycle_carry_overs.nil?
        @cycle_carry_overs = nil
        return
      end

      @cycle_carry_overs = cycle_carry_overs
    end

    # Custom attribute writer method with validation
    # @param [Object] accumulated_carry_over Value to be assigned
    def accumulated_carry_over=(accumulated_carry_over)
      if accumulated_carry_over.nil?
        @accumulated_carry_over = nil
        return
      end

      @accumulated_carry_over = accumulated_carry_over
    end

    # Custom attribute writer method with validation
    # @param [Object] available_days Value to be assigned
    def available_days=(available_days)
      if available_days.nil?
        @available_days = nil
        return
      end

      @available_days = available_days
    end

    # Custom attribute writer method with validation
    # @param [Object] total_accrued_units Value to be assigned
    def total_accrued_units=(total_accrued_units)
      if total_accrued_units.nil?
        @total_accrued_units = nil
        return
      end

      @total_accrued_units = total_accrued_units
    end

    # Custom attribute writer method with validation
    # @param [Object] total Value to be assigned
    def total=(total)
      if total.nil?
        @total = nil
        return
      end

      @total = total
    end

    # Custom attribute writer method with validation
    # @param [Object] incidences Value to be assigned
    def incidences=(incidences)
      if incidences.nil?
        @incidences = nil
        return
      end

      @incidences = incidences
    end

    # Custom attribute writer method with validation
    # @param [Object] accrued_incidences Value to be assigned
    def accrued_incidences=(accrued_incidences)
      if accrued_incidences.nil?
        @accrued_incidences = nil
        return
      end

      @accrued_incidences = accrued_incidences
    end

    # Custom attribute writer method with validation
    # @param [Object] available_incidences Value to be assigned
    def available_incidences=(available_incidences)
      if available_incidences.nil?
        @available_incidences = nil
        return
      end

      @available_incidences = available_incidences
    end

    # Custom attribute writer method with validation
    # @param [Object] policy_allowance Value to be assigned
    def policy_allowance=(policy_allowance)
      if policy_allowance.nil?
        @policy_allowance = nil
        return
      end

      @policy_allowance = policy_allowance
    end

    # Custom attribute writer method with validation
    # @param [Object] prorated_allowance_days Value to be assigned
    def prorated_allowance_days=(prorated_allowance_days)
      if prorated_allowance_days.nil?
        @prorated_allowance_days = nil
        return
      end

      @prorated_allowance_days = prorated_allowance_days
    end

    # Custom attribute writer method with validation
    # @param [Object] used_carry_over Value to be assigned
    def used_carry_over=(used_carry_over)
      if used_carry_over.nil?
        @used_carry_over = nil
        return
      end

      @used_carry_over = used_carry_over
    end

    # Custom attribute writer method with validation
    # @param [Object] used_days Value to be assigned
    def used_days=(used_days)
      if used_days.nil?
        @used_days = nil
        return
      end

      @used_days = used_days
    end

    # Custom attribute writer method with validation
    # @param [Object] used_units_until_reference_date Value to be assigned
    def used_units_until_reference_date=(used_units_until_reference_date)
      if used_units_until_reference_date.nil?
        @used_units_until_reference_date = nil
        return
      end

      @used_units_until_reference_date = used_units_until_reference_date
    end

    # Custom attribute writer method with validation
    # @param [Object] outstanding_units Value to be assigned
    def outstanding_units=(outstanding_units)
      if outstanding_units.nil?
        @outstanding_units = nil
        return
      end

      @outstanding_units = outstanding_units
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          allowance_id == o.allowance_id &&
          employee_id == o.employee_id &&
          year == o.year &&
          cycles == o.cycles &&
          cycle_carry_overs == o.cycle_carry_overs &&
          accumulated_carry_over == o.accumulated_carry_over &&
          available_days == o.available_days &&
          total_accrued_units == o.total_accrued_units &&
          total == o.total &&
          incidences == o.incidences &&
          accrued_incidences == o.accrued_incidences &&
          available_incidences == o.available_incidences &&
          max_balance_cap == o.max_balance_cap &&
          policy_allowance == o.policy_allowance &&
          prorated_allowance_days == o.prorated_allowance_days &&
          total_in_decimal == o.total_in_decimal &&
          used_carry_over == o.used_carry_over &&
          used_days == o.used_days &&
          used_units_until_reference_date == o.used_units_until_reference_date &&
          outstanding_units == o.outstanding_units
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, allowance_id, employee_id, year, cycles, cycle_carry_overs, accumulated_carry_over, available_days, total_accrued_units, total, incidences, accrued_incidences, available_incidences, max_balance_cap, policy_allowance, prorated_allowance_days, total_in_decimal, used_carry_over, used_days, used_units_until_reference_date, outstanding_units].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
