=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F::Api
  class TimeoffLeavesPostRequest < ApiModelBase
    # The employee id of the leave
    attr_accessor :employee_id

    # The leave type id
    attr_accessor :leave_type_id

    # The description of the leave
    attr_accessor :description

    # The valid start date of the leave following the format YYYY-MM-DD
    attr_accessor :start_on

    # The valid end date of the leave following the format YYYY-MM-DD
    attr_accessor :finish_on

    # If the leave is in: [beggining_of_day, end_of_day]
    attr_accessor :half_day

    # The start time of a leave
    attr_accessor :start_time

    # The hours amount in cents of a leave
    attr_accessor :hours_amount_in_cents

    # The medical leave type
    attr_accessor :medical_leave_type

    # The effective on date of a leave following the format YYYY-MM-DD
    attr_accessor :effective_on

    # The medical discharge reason of a leave
    attr_accessor :medical_discharge_reason

    # The colegiate number of a leave
    attr_accessor :colegiate_number

    # If the leave has previous relapse
    attr_accessor :has_previous_relapse

    # The leave relapse id
    attr_accessor :relapse_leave_id

    # The leave relapse on date following the format YYYY-MM-DD
    attr_accessor :relapse_on

    # The leave accident on date following the format YYYY-MM-DD
    attr_accessor :accident_on

    # The leave paternity birth on date following the format YYYY-MM-DD
    attr_accessor :paternity_birth_on

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'employee_id' => :'employee_id',
        :'leave_type_id' => :'leave_type_id',
        :'description' => :'description',
        :'start_on' => :'start_on',
        :'finish_on' => :'finish_on',
        :'half_day' => :'half_day',
        :'start_time' => :'start_time',
        :'hours_amount_in_cents' => :'hours_amount_in_cents',
        :'medical_leave_type' => :'medical_leave_type',
        :'effective_on' => :'effective_on',
        :'medical_discharge_reason' => :'medical_discharge_reason',
        :'colegiate_number' => :'colegiate_number',
        :'has_previous_relapse' => :'has_previous_relapse',
        :'relapse_leave_id' => :'relapse_leave_id',
        :'relapse_on' => :'relapse_on',
        :'accident_on' => :'accident_on',
        :'paternity_birth_on' => :'paternity_birth_on'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'employee_id' => :'String',
        :'leave_type_id' => :'String',
        :'description' => :'String',
        :'start_on' => :'String',
        :'finish_on' => :'String',
        :'half_day' => :'String',
        :'start_time' => :'String',
        :'hours_amount_in_cents' => :'Integer',
        :'medical_leave_type' => :'Integer',
        :'effective_on' => :'String',
        :'medical_discharge_reason' => :'String',
        :'colegiate_number' => :'Integer',
        :'has_previous_relapse' => :'Boolean',
        :'relapse_leave_id' => :'String',
        :'relapse_on' => :'String',
        :'accident_on' => :'String',
        :'paternity_birth_on' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::Api::TimeoffLeavesPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::Api::TimeoffLeavesPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'employee_id')
        self.employee_id = attributes[:'employee_id']
      else
        self.employee_id = nil
      end

      if attributes.key?(:'leave_type_id')
        self.leave_type_id = attributes[:'leave_type_id']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'start_on')
        self.start_on = attributes[:'start_on']
      else
        self.start_on = nil
      end

      if attributes.key?(:'finish_on')
        self.finish_on = attributes[:'finish_on']
      end

      if attributes.key?(:'half_day')
        self.half_day = attributes[:'half_day']
      end

      if attributes.key?(:'start_time')
        self.start_time = attributes[:'start_time']
      end

      if attributes.key?(:'hours_amount_in_cents')
        self.hours_amount_in_cents = attributes[:'hours_amount_in_cents']
      end

      if attributes.key?(:'medical_leave_type')
        self.medical_leave_type = attributes[:'medical_leave_type']
      end

      if attributes.key?(:'effective_on')
        self.effective_on = attributes[:'effective_on']
      end

      if attributes.key?(:'medical_discharge_reason')
        self.medical_discharge_reason = attributes[:'medical_discharge_reason']
      end

      if attributes.key?(:'colegiate_number')
        self.colegiate_number = attributes[:'colegiate_number']
      end

      if attributes.key?(:'has_previous_relapse')
        self.has_previous_relapse = attributes[:'has_previous_relapse']
      end

      if attributes.key?(:'relapse_leave_id')
        self.relapse_leave_id = attributes[:'relapse_leave_id']
      end

      if attributes.key?(:'relapse_on')
        self.relapse_on = attributes[:'relapse_on']
      end

      if attributes.key?(:'accident_on')
        self.accident_on = attributes[:'accident_on']
      end

      if attributes.key?(:'paternity_birth_on')
        self.paternity_birth_on = attributes[:'paternity_birth_on']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @employee_id.nil?
        invalid_properties.push('invalid value for "employee_id", employee_id cannot be nil.')
      end

      if @start_on.nil?
        invalid_properties.push('invalid value for "start_on", start_on cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @employee_id.nil?
      return false if @start_on.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] employee_id Value to be assigned
    def employee_id=(employee_id)
      if employee_id.nil?
        @employee_id = nil
        return
      end

      @employee_id = employee_id
    end

    # Custom attribute writer method with validation
    # @param [Object] start_on Value to be assigned
    def start_on=(start_on)
      if start_on.nil?
        @start_on = nil
        return
      end

      @start_on = start_on
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          employee_id == o.employee_id &&
          leave_type_id == o.leave_type_id &&
          description == o.description &&
          start_on == o.start_on &&
          finish_on == o.finish_on &&
          half_day == o.half_day &&
          start_time == o.start_time &&
          hours_amount_in_cents == o.hours_amount_in_cents &&
          medical_leave_type == o.medical_leave_type &&
          effective_on == o.effective_on &&
          medical_discharge_reason == o.medical_discharge_reason &&
          colegiate_number == o.colegiate_number &&
          has_previous_relapse == o.has_previous_relapse &&
          relapse_leave_id == o.relapse_leave_id &&
          relapse_on == o.relapse_on &&
          accident_on == o.accident_on &&
          paternity_birth_on == o.paternity_birth_on
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [employee_id, leave_type_id, description, start_on, finish_on, half_day, start_time, hours_amount_in_cents, medical_leave_type, effective_on, medical_discharge_reason, colegiate_number, has_previous_relapse, relapse_leave_id, relapse_on, accident_on, paternity_birth_on].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
