=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F::Api
  class TimeoffAllowancesIdPutRequest < ApiModelBase
    attr_accessor :id

    # Only for Allowances based on worked time. It represents how many units you need to work to be granted allowance units
    attr_accessor :accrued_denominator_in_cents

    # Only for Allowances based on worked time. It represents how many units you are given per unit of time worked
    attr_accessor :accrued_factor_in_cents

    # Indicates how the allowance units are accrued. For example all_days means all allowance days are given on the first day of the cycle.
    attr_accessor :available_days

    # How many units can carry over between cycles multiplied by 100
    attr_accessor :carry_over_units_in_cents

    # This setting flags if units taken during a bank holiday should be deducted or not from allowance.
    attr_accessor :count_holiday_as_workable

    # Indicates if the allowance is based on working on calendar days.
    attr_accessor :days_type

    # When does the carryover expire in months.
    attr_accessor :expire_in_months

    # Defines duration of the allowance cycles. Can be \"yearly\", \"monthly_flexible\" or \"lifetime\"
    attr_accessor :frequency

    # Base amount of holiday allowance units multiplied by 100
    attr_accessor :holiday_allowance_in_cents

    # An array of leave type ids associated with that allowance
    attr_accessor :leave_type_ids

    # Maximum the allowance can reach on accrued
    attr_accessor :maximum_amount_in_cents

    # Allowance name set by the user
    attr_accessor :name

    # Whether the allowance allows to request more days than available.
    attr_accessor :negative_counter_type

    # Indicates the position in the allowance when rendering them in UI
    attr_accessor :position

    # Whether the allowance has proration enabled or not.
    attr_accessor :proration_type

    # Whether the allowance days are prorated or not
    attr_accessor :pto_proratio_enabled

    # Configures how leaves duration is handled.
    attr_accessor :range_type

    # How the accrued units of the allowance are rounded. It depends if the allowance is set in hours or days.
    attr_accessor :rounding

    # In case the allowance has tenure periods, when is this tenure applied.
    attr_accessor :tenure_period_transition

    # Whether the allowance has tenure periods enabled or not.
    attr_accessor :tenure_periods_enabled

    # The tenure periods associated with the allowance.
    attr_accessor :tenure_periods

    # Flag to indicate if there is unlimited accrual.
    attr_accessor :unlimited_accrued_hours

    # Flag to indicate if there is unlimited carry over.
    attr_accessor :unlimited_carry_over

    # Boolean to flag if carryover does not expire
    attr_accessor :unlimited_carry_over_expiration

    # Flag to indicate that the allowance has unlimited available days
    attr_accessor :unlimited_holidays

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'accrued_denominator_in_cents' => :'accrued_denominator_in_cents',
        :'accrued_factor_in_cents' => :'accrued_factor_in_cents',
        :'available_days' => :'available_days',
        :'carry_over_units_in_cents' => :'carry_over_units_in_cents',
        :'count_holiday_as_workable' => :'count_holiday_as_workable',
        :'days_type' => :'days_type',
        :'expire_in_months' => :'expire_in_months',
        :'frequency' => :'frequency',
        :'holiday_allowance_in_cents' => :'holiday_allowance_in_cents',
        :'leave_type_ids' => :'leave_type_ids',
        :'maximum_amount_in_cents' => :'maximum_amount_in_cents',
        :'name' => :'name',
        :'negative_counter_type' => :'negative_counter_type',
        :'position' => :'position',
        :'proration_type' => :'proration_type',
        :'pto_proratio_enabled' => :'pto_proratio_enabled',
        :'range_type' => :'range_type',
        :'rounding' => :'rounding',
        :'tenure_period_transition' => :'tenure_period_transition',
        :'tenure_periods_enabled' => :'tenure_periods_enabled',
        :'tenure_periods' => :'tenure_periods',
        :'unlimited_accrued_hours' => :'unlimited_accrued_hours',
        :'unlimited_carry_over' => :'unlimited_carry_over',
        :'unlimited_carry_over_expiration' => :'unlimited_carry_over_expiration',
        :'unlimited_holidays' => :'unlimited_holidays'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'accrued_denominator_in_cents' => :'Integer',
        :'accrued_factor_in_cents' => :'Integer',
        :'available_days' => :'String',
        :'carry_over_units_in_cents' => :'Integer',
        :'count_holiday_as_workable' => :'Boolean',
        :'days_type' => :'String',
        :'expire_in_months' => :'Integer',
        :'frequency' => :'String',
        :'holiday_allowance_in_cents' => :'Integer',
        :'leave_type_ids' => :'Array<String>',
        :'maximum_amount_in_cents' => :'Integer',
        :'name' => :'String',
        :'negative_counter_type' => :'String',
        :'position' => :'Integer',
        :'proration_type' => :'String',
        :'pto_proratio_enabled' => :'Boolean',
        :'range_type' => :'String',
        :'rounding' => :'String',
        :'tenure_period_transition' => :'String',
        :'tenure_periods_enabled' => :'Boolean',
        :'tenure_periods' => :'Array<Object>',
        :'unlimited_accrued_hours' => :'Boolean',
        :'unlimited_carry_over' => :'Boolean',
        :'unlimited_carry_over_expiration' => :'Boolean',
        :'unlimited_holidays' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::Api::TimeoffAllowancesIdPutRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::Api::TimeoffAllowancesIdPutRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'accrued_denominator_in_cents')
        self.accrued_denominator_in_cents = attributes[:'accrued_denominator_in_cents']
      end

      if attributes.key?(:'accrued_factor_in_cents')
        self.accrued_factor_in_cents = attributes[:'accrued_factor_in_cents']
      end

      if attributes.key?(:'available_days')
        self.available_days = attributes[:'available_days']
      end

      if attributes.key?(:'carry_over_units_in_cents')
        self.carry_over_units_in_cents = attributes[:'carry_over_units_in_cents']
      end

      if attributes.key?(:'count_holiday_as_workable')
        self.count_holiday_as_workable = attributes[:'count_holiday_as_workable']
      end

      if attributes.key?(:'days_type')
        self.days_type = attributes[:'days_type']
      end

      if attributes.key?(:'expire_in_months')
        self.expire_in_months = attributes[:'expire_in_months']
      end

      if attributes.key?(:'frequency')
        self.frequency = attributes[:'frequency']
      end

      if attributes.key?(:'holiday_allowance_in_cents')
        self.holiday_allowance_in_cents = attributes[:'holiday_allowance_in_cents']
      end

      if attributes.key?(:'leave_type_ids')
        if (value = attributes[:'leave_type_ids']).is_a?(Array)
          self.leave_type_ids = value
        end
      end

      if attributes.key?(:'maximum_amount_in_cents')
        self.maximum_amount_in_cents = attributes[:'maximum_amount_in_cents']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'negative_counter_type')
        self.negative_counter_type = attributes[:'negative_counter_type']
      end

      if attributes.key?(:'position')
        self.position = attributes[:'position']
      end

      if attributes.key?(:'proration_type')
        self.proration_type = attributes[:'proration_type']
      end

      if attributes.key?(:'pto_proratio_enabled')
        self.pto_proratio_enabled = attributes[:'pto_proratio_enabled']
      end

      if attributes.key?(:'range_type')
        self.range_type = attributes[:'range_type']
      end

      if attributes.key?(:'rounding')
        self.rounding = attributes[:'rounding']
      end

      if attributes.key?(:'tenure_period_transition')
        self.tenure_period_transition = attributes[:'tenure_period_transition']
      end

      if attributes.key?(:'tenure_periods_enabled')
        self.tenure_periods_enabled = attributes[:'tenure_periods_enabled']
      end

      if attributes.key?(:'tenure_periods')
        if (value = attributes[:'tenure_periods']).is_a?(Array)
          self.tenure_periods = value
        end
      end

      if attributes.key?(:'unlimited_accrued_hours')
        self.unlimited_accrued_hours = attributes[:'unlimited_accrued_hours']
      end

      if attributes.key?(:'unlimited_carry_over')
        self.unlimited_carry_over = attributes[:'unlimited_carry_over']
      end

      if attributes.key?(:'unlimited_carry_over_expiration')
        self.unlimited_carry_over_expiration = attributes[:'unlimited_carry_over_expiration']
      end

      if attributes.key?(:'unlimited_holidays')
        self.unlimited_holidays = attributes[:'unlimited_holidays']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      available_days_validator = EnumAttributeValidator.new('String', ["all_days", "generated_days", "generated_days_monthly", "generated_days_monthly_first_day", "monthly_fifteenth", "mensiversary", "bimonthly_first_and_fifteenth", "bimonthly_fifteenth_and_last"])
      return false unless available_days_validator.valid?(@available_days)
      days_type_validator = EnumAttributeValidator.new('String', ["working_days", "natural_days", "natural_days_only_range", "french_calendar_days", "french_ouvres"])
      return false unless days_type_validator.valid?(@days_type)
      frequency_validator = EnumAttributeValidator.new('String', ["monthly_flexible", "yearly", "lifetime"])
      return false unless frequency_validator.valid?(@frequency)
      negative_counter_type_validator = EnumAttributeValidator.new('String', ["negative_counter_disabled", "negative_counter_enabled"])
      return false unless negative_counter_type_validator.valid?(@negative_counter_type)
      proration_type_validator = EnumAttributeValidator.new('String', ["proration_enabled", "proration_disabled"])
      return false unless proration_type_validator.valid?(@proration_type)
      range_type_validator = EnumAttributeValidator.new('String', ["exact_range", "extra_non_working_days_at_end"])
      return false unless range_type_validator.valid?(@range_type)
      rounding_validator = EnumAttributeValidator.new('String', ["half_day", "decimals", "quarters", "round_up"])
      return false unless rounding_validator.valid?(@rounding)
      tenure_period_transition_validator = EnumAttributeValidator.new('String', ["beginning_of_cycle", "end_of_cycle", "after_milestone"])
      return false unless tenure_period_transition_validator.valid?(@tenure_period_transition)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        @id = nil
        return
      end

      @id = id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] available_days Object to be assigned
    def available_days=(available_days)
      validator = EnumAttributeValidator.new('String', ["all_days", "generated_days", "generated_days_monthly", "generated_days_monthly_first_day", "monthly_fifteenth", "mensiversary", "bimonthly_first_and_fifteenth", "bimonthly_fifteenth_and_last"])
      unless validator.valid?(available_days)
        fail ArgumentError, "invalid value for \"available_days\", must be one of #{validator.allowable_values}."
      end
      @available_days = available_days
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] days_type Object to be assigned
    def days_type=(days_type)
      validator = EnumAttributeValidator.new('String', ["working_days", "natural_days", "natural_days_only_range", "french_calendar_days", "french_ouvres"])
      unless validator.valid?(days_type)
        fail ArgumentError, "invalid value for \"days_type\", must be one of #{validator.allowable_values}."
      end
      @days_type = days_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] frequency Object to be assigned
    def frequency=(frequency)
      validator = EnumAttributeValidator.new('String', ["monthly_flexible", "yearly", "lifetime"])
      unless validator.valid?(frequency)
        fail ArgumentError, "invalid value for \"frequency\", must be one of #{validator.allowable_values}."
      end
      @frequency = frequency
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] negative_counter_type Object to be assigned
    def negative_counter_type=(negative_counter_type)
      validator = EnumAttributeValidator.new('String', ["negative_counter_disabled", "negative_counter_enabled"])
      unless validator.valid?(negative_counter_type)
        fail ArgumentError, "invalid value for \"negative_counter_type\", must be one of #{validator.allowable_values}."
      end
      @negative_counter_type = negative_counter_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] proration_type Object to be assigned
    def proration_type=(proration_type)
      validator = EnumAttributeValidator.new('String', ["proration_enabled", "proration_disabled"])
      unless validator.valid?(proration_type)
        fail ArgumentError, "invalid value for \"proration_type\", must be one of #{validator.allowable_values}."
      end
      @proration_type = proration_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] range_type Object to be assigned
    def range_type=(range_type)
      validator = EnumAttributeValidator.new('String', ["exact_range", "extra_non_working_days_at_end"])
      unless validator.valid?(range_type)
        fail ArgumentError, "invalid value for \"range_type\", must be one of #{validator.allowable_values}."
      end
      @range_type = range_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] rounding Object to be assigned
    def rounding=(rounding)
      validator = EnumAttributeValidator.new('String', ["half_day", "decimals", "quarters", "round_up"])
      unless validator.valid?(rounding)
        fail ArgumentError, "invalid value for \"rounding\", must be one of #{validator.allowable_values}."
      end
      @rounding = rounding
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] tenure_period_transition Object to be assigned
    def tenure_period_transition=(tenure_period_transition)
      validator = EnumAttributeValidator.new('String', ["beginning_of_cycle", "end_of_cycle", "after_milestone"])
      unless validator.valid?(tenure_period_transition)
        fail ArgumentError, "invalid value for \"tenure_period_transition\", must be one of #{validator.allowable_values}."
      end
      @tenure_period_transition = tenure_period_transition
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          accrued_denominator_in_cents == o.accrued_denominator_in_cents &&
          accrued_factor_in_cents == o.accrued_factor_in_cents &&
          available_days == o.available_days &&
          carry_over_units_in_cents == o.carry_over_units_in_cents &&
          count_holiday_as_workable == o.count_holiday_as_workable &&
          days_type == o.days_type &&
          expire_in_months == o.expire_in_months &&
          frequency == o.frequency &&
          holiday_allowance_in_cents == o.holiday_allowance_in_cents &&
          leave_type_ids == o.leave_type_ids &&
          maximum_amount_in_cents == o.maximum_amount_in_cents &&
          name == o.name &&
          negative_counter_type == o.negative_counter_type &&
          position == o.position &&
          proration_type == o.proration_type &&
          pto_proratio_enabled == o.pto_proratio_enabled &&
          range_type == o.range_type &&
          rounding == o.rounding &&
          tenure_period_transition == o.tenure_period_transition &&
          tenure_periods_enabled == o.tenure_periods_enabled &&
          tenure_periods == o.tenure_periods &&
          unlimited_accrued_hours == o.unlimited_accrued_hours &&
          unlimited_carry_over == o.unlimited_carry_over &&
          unlimited_carry_over_expiration == o.unlimited_carry_over_expiration &&
          unlimited_holidays == o.unlimited_holidays
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, accrued_denominator_in_cents, accrued_factor_in_cents, available_days, carry_over_units_in_cents, count_holiday_as_workable, days_type, expire_in_months, frequency, holiday_allowance_in_cents, leave_type_ids, maximum_amount_in_cents, name, negative_counter_type, position, proration_type, pto_proratio_enabled, range_type, rounding, tenure_period_transition, tenure_periods_enabled, tenure_periods, unlimited_accrued_hours, unlimited_carry_over, unlimited_carry_over_expiration, unlimited_holidays].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
