=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F
  class TimePlanningPlanningVersionsPostRequest < ApiModelBase
    # Planning version start date
    attr_accessor :effective_at

    # Type of planning tool (shift_management, work_schedules, contract_hours)
    attr_accessor :planning_tool

    # Amount of rest days per week if applicable (in cents)
    attr_accessor :number_of_rest_days_in_cents

    # Employee identifier
    attr_accessor :employee_id

    # Work schedule identifier to include if applicable
    attr_accessor :schedule_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'effective_at' => :'effective_at',
        :'planning_tool' => :'planning_tool',
        :'number_of_rest_days_in_cents' => :'number_of_rest_days_in_cents',
        :'employee_id' => :'employee_id',
        :'schedule_id' => :'schedule_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'effective_at' => :'String',
        :'planning_tool' => :'String',
        :'number_of_rest_days_in_cents' => :'Integer',
        :'employee_id' => :'String',
        :'schedule_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::TimePlanningPlanningVersionsPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::TimePlanningPlanningVersionsPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'effective_at')
        self.effective_at = attributes[:'effective_at']
      else
        self.effective_at = nil
      end

      if attributes.key?(:'planning_tool')
        self.planning_tool = attributes[:'planning_tool']
      else
        self.planning_tool = nil
      end

      if attributes.key?(:'number_of_rest_days_in_cents')
        self.number_of_rest_days_in_cents = attributes[:'number_of_rest_days_in_cents']
      end

      if attributes.key?(:'employee_id')
        self.employee_id = attributes[:'employee_id']
      else
        self.employee_id = nil
      end

      if attributes.key?(:'schedule_id')
        self.schedule_id = attributes[:'schedule_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @effective_at.nil?
        invalid_properties.push('invalid value for "effective_at", effective_at cannot be nil.')
      end

      if @planning_tool.nil?
        invalid_properties.push('invalid value for "planning_tool", planning_tool cannot be nil.')
      end

      if @employee_id.nil?
        invalid_properties.push('invalid value for "employee_id", employee_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @effective_at.nil?
      return false if @planning_tool.nil?
      return false if @employee_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] effective_at Value to be assigned
    def effective_at=(effective_at)
      if effective_at.nil?
        @effective_at = nil
        return
      end

      @effective_at = effective_at
    end

    # Custom attribute writer method with validation
    # @param [Object] planning_tool Value to be assigned
    def planning_tool=(planning_tool)
      if planning_tool.nil?
        @planning_tool = nil
        return
      end

      @planning_tool = planning_tool
    end

    # Custom attribute writer method with validation
    # @param [Object] employee_id Value to be assigned
    def employee_id=(employee_id)
      if employee_id.nil?
        @employee_id = nil
        return
      end

      @employee_id = employee_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          effective_at == o.effective_at &&
          planning_tool == o.planning_tool &&
          number_of_rest_days_in_cents == o.number_of_rest_days_in_cents &&
          employee_id == o.employee_id &&
          schedule_id == o.schedule_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [effective_at, planning_tool, number_of_rest_days_in_cents, employee_id, schedule_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
