=begin
#Factorial API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2026-07-01

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module F
  class TrainingsTrainingClassesPostRequest < ApiModelBase
    # Class name
    attr_accessor :name

    # Class description
    attr_accessor :description

    # Traning class start date
    attr_accessor :start_date

    # Traning class end date
    attr_accessor :end_date

    # Training the class belongs to
    attr_accessor :training_id

    # Company identifier the class belongs to
    attr_accessor :company_id

    # access_id associated to the employee that creates the training class, refers to employees/employees endpoint.
    attr_accessor :author_id

    # Training-related expenses, such as instructor fees, materials, venue, and logistics.
    attr_accessor :cost

    # Amount of training expenses covered by financial aid or grants for this group.
    attr_accessor :subsidized_cost

    # General business expenses related to training, such as utilities and administrative fees.
    attr_accessor :indirect_cost

    # Cost of all employees' time spent on the course.
    attr_accessor :salary_cost

    # Payment status of the training class.
    attr_accessor :payment_status

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'description' => :'description',
        :'start_date' => :'start_date',
        :'end_date' => :'end_date',
        :'training_id' => :'training_id',
        :'company_id' => :'company_id',
        :'author_id' => :'author_id',
        :'cost' => :'cost',
        :'subsidized_cost' => :'subsidized_cost',
        :'indirect_cost' => :'indirect_cost',
        :'salary_cost' => :'salary_cost',
        :'payment_status' => :'payment_status'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'description' => :'String',
        :'start_date' => :'String',
        :'end_date' => :'String',
        :'training_id' => :'String',
        :'company_id' => :'String',
        :'author_id' => :'String',
        :'cost' => :'String',
        :'subsidized_cost' => :'String',
        :'indirect_cost' => :'String',
        :'salary_cost' => :'String',
        :'payment_status' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `F::TrainingsTrainingClassesPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `F::TrainingsTrainingClassesPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      else
        self.start_date = nil
      end

      if attributes.key?(:'end_date')
        self.end_date = attributes[:'end_date']
      else
        self.end_date = nil
      end

      if attributes.key?(:'training_id')
        self.training_id = attributes[:'training_id']
      else
        self.training_id = nil
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      else
        self.company_id = nil
      end

      if attributes.key?(:'author_id')
        self.author_id = attributes[:'author_id']
      else
        self.author_id = nil
      end

      if attributes.key?(:'cost')
        self.cost = attributes[:'cost']
      else
        self.cost = nil
      end

      if attributes.key?(:'subsidized_cost')
        self.subsidized_cost = attributes[:'subsidized_cost']
      else
        self.subsidized_cost = nil
      end

      if attributes.key?(:'indirect_cost')
        self.indirect_cost = attributes[:'indirect_cost']
      else
        self.indirect_cost = nil
      end

      if attributes.key?(:'salary_cost')
        self.salary_cost = attributes[:'salary_cost']
      else
        self.salary_cost = nil
      end

      if attributes.key?(:'payment_status')
        self.payment_status = attributes[:'payment_status']
      else
        self.payment_status = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @start_date.nil?
        invalid_properties.push('invalid value for "start_date", start_date cannot be nil.')
      end

      if @end_date.nil?
        invalid_properties.push('invalid value for "end_date", end_date cannot be nil.')
      end

      if @training_id.nil?
        invalid_properties.push('invalid value for "training_id", training_id cannot be nil.')
      end

      if @company_id.nil?
        invalid_properties.push('invalid value for "company_id", company_id cannot be nil.')
      end

      if @author_id.nil?
        invalid_properties.push('invalid value for "author_id", author_id cannot be nil.')
      end

      if @cost.nil?
        invalid_properties.push('invalid value for "cost", cost cannot be nil.')
      end

      if @subsidized_cost.nil?
        invalid_properties.push('invalid value for "subsidized_cost", subsidized_cost cannot be nil.')
      end

      if @indirect_cost.nil?
        invalid_properties.push('invalid value for "indirect_cost", indirect_cost cannot be nil.')
      end

      if @salary_cost.nil?
        invalid_properties.push('invalid value for "salary_cost", salary_cost cannot be nil.')
      end

      if @payment_status.nil?
        invalid_properties.push('invalid value for "payment_status", payment_status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @start_date.nil?
      return false if @end_date.nil?
      return false if @training_id.nil?
      return false if @company_id.nil?
      return false if @author_id.nil?
      return false if @cost.nil?
      return false if @subsidized_cost.nil?
      return false if @indirect_cost.nil?
      return false if @salary_cost.nil?
      return false if @payment_status.nil?
      payment_status_validator = EnumAttributeValidator.new('String', ["paid", "pending"])
      return false unless payment_status_validator.valid?(@payment_status)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] start_date Value to be assigned
    def start_date=(start_date)
      if start_date.nil?
        fail ArgumentError, 'start_date cannot be nil'
      end

      @start_date = start_date
    end

    # Custom attribute writer method with validation
    # @param [Object] end_date Value to be assigned
    def end_date=(end_date)
      if end_date.nil?
        fail ArgumentError, 'end_date cannot be nil'
      end

      @end_date = end_date
    end

    # Custom attribute writer method with validation
    # @param [Object] training_id Value to be assigned
    def training_id=(training_id)
      if training_id.nil?
        fail ArgumentError, 'training_id cannot be nil'
      end

      @training_id = training_id
    end

    # Custom attribute writer method with validation
    # @param [Object] company_id Value to be assigned
    def company_id=(company_id)
      if company_id.nil?
        fail ArgumentError, 'company_id cannot be nil'
      end

      @company_id = company_id
    end

    # Custom attribute writer method with validation
    # @param [Object] author_id Value to be assigned
    def author_id=(author_id)
      if author_id.nil?
        fail ArgumentError, 'author_id cannot be nil'
      end

      @author_id = author_id
    end

    # Custom attribute writer method with validation
    # @param [Object] cost Value to be assigned
    def cost=(cost)
      if cost.nil?
        fail ArgumentError, 'cost cannot be nil'
      end

      @cost = cost
    end

    # Custom attribute writer method with validation
    # @param [Object] subsidized_cost Value to be assigned
    def subsidized_cost=(subsidized_cost)
      if subsidized_cost.nil?
        fail ArgumentError, 'subsidized_cost cannot be nil'
      end

      @subsidized_cost = subsidized_cost
    end

    # Custom attribute writer method with validation
    # @param [Object] indirect_cost Value to be assigned
    def indirect_cost=(indirect_cost)
      if indirect_cost.nil?
        fail ArgumentError, 'indirect_cost cannot be nil'
      end

      @indirect_cost = indirect_cost
    end

    # Custom attribute writer method with validation
    # @param [Object] salary_cost Value to be assigned
    def salary_cost=(salary_cost)
      if salary_cost.nil?
        fail ArgumentError, 'salary_cost cannot be nil'
      end

      @salary_cost = salary_cost
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] payment_status Object to be assigned
    def payment_status=(payment_status)
      validator = EnumAttributeValidator.new('String', ["paid", "pending"])
      unless validator.valid?(payment_status)
        fail ArgumentError, "invalid value for \"payment_status\", must be one of #{validator.allowable_values}."
      end
      @payment_status = payment_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          description == o.description &&
          start_date == o.start_date &&
          end_date == o.end_date &&
          training_id == o.training_id &&
          company_id == o.company_id &&
          author_id == o.author_id &&
          cost == o.cost &&
          subsidized_cost == o.subsidized_cost &&
          indirect_cost == o.indirect_cost &&
          salary_cost == o.salary_cost &&
          payment_status == o.payment_status
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, description, start_date, end_date, training_id, company_id, author_id, cost, subsidized_cost, indirect_cost, salary_cost, payment_status].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
